{
 "title": "Trigger and HSI",
 "tags": [
  "Subsystem",
  "v3.2.1"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SHOW TAG VALUES WITH KEY=\"partition_id\" WHERE $timeFilter"
   },
   {
    "name": "series",
    "query": "SHOW SERIES WHERE \"partition_id\"='${partition}' AND $timeFilter"
   },
   {
    "name": "field",
    "query": "SHOW FIELD KEYS FROM \"dunedaq.timinglibs.${series}.Info\""
   },
   {
    "name": "application",
    "label": "Trigger App",
    "query": "SHOW TAG VALUES FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WITH KEY=\"source_id\" WHERE \"partition_id\"='${partition}' AND $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "HSI Average Buffer Occupancy",
   "type": "timeseries",
   "description": "Only available for real HSI",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Average buffer occupancy",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "query": "SELECT \"average_buffer_occupancy\" FROM \"dunedaq.timinglibs.hsireadoutinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter",
     "select": [
      [
       { "params": [ "average_buffer_occupancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02_coldbox" }
     ]
    }
   ]
  },
  {
   "title": "Failed HSI Events ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "query": "SELECT last(\"failed_to_send_hsi_events_counter\") FROM \"dunedaq.timinglibs.${series}.Info\" WHERE (\"partition_id\" = 'maroda_test') AND $timeFilter ",
     "select": [
      [
       {
        "params": [
         "failed_to_send_hsi_events_counter"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Failed to sent HSI",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "query": "SELECT mean(\"failed_to_send_hsi_events_counter\") FROM \"dunedaq.timinglibs.${series}.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       {
        "params": [
         "failed_to_send_hsi_events_counter"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HSI events sent counter",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "query": "SELECT last(\"sent_hsi_events_counter\") FROM \"dunedaq.timinglibs.${series}.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter",
     "select": [
      [
       { "params": [ "sent_hsi_events_counter" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02_coldbox" }
     ]
    },
    {
     "alias": "HSI events ${field} counter",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "query": "SELECT last(\"${field}_hsi_events_counter\") FROM \"dunedaq.timinglibs.${series}.Info\" WHERE (\"partition_id\"='${partition}') AND $timeFilter",
     "select": [
      [
       { "params": [ "readout_hsi_events_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last ${field} Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "query": "SELECT last(\"last_${field}_timestamp\") FROM \"dunedaq.timinglibs.${series}.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter",
     "select": [
      [
       { "params": [ "last_readout_timestamp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Last Sent Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "query": "SELECT last(\"last_sent_timestamp\") FROM \"dunedaq.timinglibs.${series}.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter ",
     "select": [
      [
       { "params": [ "last_sent_timestamp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Trigger Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Generated triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_td_total_count\")), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" ='${partition}') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Sent triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_td_sent_count\")), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Paused triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(sum(\"td_paused_count\"), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time(500ms)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Inhibited triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_td_inhibited_count\")), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "HSI Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "${field} HSI triggers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.timinglibs.fakehsieventgeneratorinfo.Info",
     "query": "SELECT non_negative_derivative(sum(\"${field}_hsi_events_counter\"), 1s) FROM \"dunedaq.timinglibs.${series}.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time(500ms) fill(null)",
     "select": [
      [
       { "params": [ "generated_hsi_events_counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_hsi.fhsig" }
     ]
    },
    {
     "alias": "Sent HSI triggers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.timinglibs.fakehsieventgeneratorinfo.Info",
     "query": "SELECT non_negative_derivative(sum(\"${field}_hsi_events_counter\"), 1s) FROM \"dunedaq.timinglibs.${series}.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time(500ms) fill(null)",
     "select": [
      [
       { "params": [ "sent_hsi_events_counter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_hsi.fhsig" }
     ]
    }
   ]
  }
 ]
}