# Default values for dune-grafana-dashboards.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

labels:
  grafana_dashboard: "1"

annotations:
  k8s-sidecar-target-directory: /tmp/dashboards/DUNE
