{
 "title": "Readout",
 "tags": [ "Coldbox" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SHOW SERIES FROM \"dunedaq.appfwk.appinfo.Info\"  where $timeFilter"
   },
   {
    "name": "readout_app",
    "label": "Readout application",
    "query": "SHOW  SERIES  FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" "
   },
   {
    "name": "readout_module",
    "label": "Readout module",
    "query": "SHOW  SERIES  FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Single elements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Software TPG rates for ${readout_app} ${readout_module}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Sent TPG ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dunedaq.readout.readoutinfo.RawDataProcessorInfo",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_tps_sent\")), 1s) FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" WHERE (\"source_id\" = '${partition}_${readout_app}.${readout_module}') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "num_tps_sent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_ruemu0.datahandler_0"
        }
       ]
      },
      {
       "alias": "Sent TPG Sets",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dunedaq.readout.readoutinfo.RawDataProcessorInfo",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_tpsets_sent\")), 1s) FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" WHERE (\"source_id\" = '${partition}_${readout_app}.${readout_module}') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "num_tps_sent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_ruemu0.datahandler_0"
        }
       ]
      },
      {
       "alias": "Dropped TPG",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dunedaq.readout.readoutinfo.RawDataProcessorInfo",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_tps_dropped\")), 1s) FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" WHERE (\"source_id\" = '${partition}_${readout_app}.${readout_module}') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "num_tps_sent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_ruemu0.datahandler_0"
        }
       ]
      },
      {
       "alias": "TPG Hit",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dunedaq.readout.readoutinfo.RawDataProcessorInfo",
       "query": "SELECT sum(\"rate_tp_hits\") FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" WHERE  (\"source_id\" = '${partition}_${readout_app}.${readout_module}') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "rate_tp_hits" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_ruemu0.datahandler_0"
        }
       ]
      }
     ]
    },
    {
     "title": "Buffers - Operational rates for ${readout_app} ${readout_module}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "alias": "Cleanups",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dunedaq.readout.readoutinfo.RequestHandlerInfo",
       "query": "SELECT mean(\"num_buffer_cleanups\") FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" = '${partition}_${readout_app}.${readout_module}') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "num_buffer_cleanups" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_ruemu0.datahandler_1"
        }
       ]
      },
      {
       "alias": "Overwritten",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dunedaq.readout.readoutinfo.ReadoutInfo",
       "query": "SELECT mean(\"num_payloads_overwritten\") FROM \"dunedaq.readout.readoutinfo.ReadoutInfo\" WHERE  (\"source_id\" = '${partition}_${readout_app}.${readout_module}')  AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "num_payloads_overwritten" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_ruemu0.datahandler_1"
        }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total software TPG rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sent TPG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_tps_sent\")), 1s) FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Sent TPG Sets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_tpsets_sent\")), 1s) FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Dropped TPG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_tps_dropped\")), 1s) FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "TPG Hit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT sum(\"rate_tp_hits\") FROM \"dunedaq.readout.readoutinfo.RawDataProcessorInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate_tp_hits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers - Number of elements",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.ReadoutInfo",
     "query": "SELECT mean(\"num_buffer_elements\") FROM \"dunedaq.readout.readoutinfo.ReadoutInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "num_buffer_elements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "alias": "Total ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests\")), 1s) FROM \"dunedaq.readout.readoutinfo.ReadoutInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Found",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_found\")), 1s) FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_found" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Delayed ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_delayed\")), 1s) FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_delayed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Bad ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_bad\")), 1s) FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_bad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Old window",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_old_window\")), 1s) FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Timing out ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_timed_out\")), 1s) FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Uncategorized",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_uncategorized\")), 1s) FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_uncategorized" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend receiving rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.ReadoutInfo",
     "query": "SELECT mean(\"rate_payloads_consumed\") FROM \"dunedaq.readout.readoutinfo.ReadoutInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "rate_payloads_consumed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers - Operational rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "alias": "Cleanups",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_buffer_cleanups\")), 1s) FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_buffer_cleanups" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    },
    {
     "alias": "Overwritten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_payloads_overwritten\")), 1s) FROM \"dunedaq.readout.readoutinfo.ReadoutInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_payloads_overwritten" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Waiting requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.readoutinfo.RequestHandlerInfo",
     "query": "SELECT sum(\"num_requests_waiting\") FROM \"dunedaq.readout.readoutinfo.RequestHandlerInfo\" WHERE (\"source_id\" =~ /${partition}_.*\\.datahandler_\\d+/) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "num_requests_waiting" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Felix rates",
   "type": "timeseries",
   "description": "Group this by source_id for different e_links",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_chunks_processed\")), 1s) FROM \"dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo\" WHERE (\"source_id\" =~ /${partition}_.*/) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "num_chunks_processed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": ":{USER}_test_ruflx0.flxcard_1.elink_0_1_1"
      }
     ]
    }
   ]
  }
 ]
}