{
 "title": "Trigger Flow",
 "tags": [
  "v3.2.1",
  "Subsystem"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SHOW TAG VALUES WITH KEY=\"partition_id\" where $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Module Level Trigger",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Total TD rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_total_count\"), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC Received Count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_received_count\"), 10s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "tc_received_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "Sent TD rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_sent_count\"), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = 'np02-coldbox' AND \"source_id\" = 'np02-coldbox.trigger.mlt') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "Inhibited TD rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_inhibited_count\"), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "td_inhibited_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD Paused rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_paused_count\"), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "Error rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_queue_timeout_expired_err_count\"), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       {
        "params": [
         "td_queue_timeout_expired_err_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TPChannelFilter receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.tpchannelfilterinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"received_count\"), 1s) FROM \"dunedaq.trigger.tpchannelfilterinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null) ",
     "select": [
      [
       { "params": [ "received_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      {
       "condition": "AND",
       "key": "source_id",
       "operator": "=",
       "value": "np02-coldbox.trigger.channelfilter_ru0_link0"
      }
     ]
    }
   ]
  },
  {
   "title": "TPChannelFilter sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.tpchannelfilterinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"sent_count\"), 1s) FROM \"dunedaq.trigger.tpchannelfilterinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "sent_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      {
       "condition": "AND",
       "key": "source_id",
       "operator": "=",
       "value": "np02-coldbox.trigger.channelfilter_ru0_link6"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TPHeartbeatMaker receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "measurement": "dunedaq.trigger.faketpcreatorheartbeatmakerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tpset_received_count\"),1s) FROM \"dunedaq.trigger.faketpcreatorheartbeatmakerinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "tpset_received_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      {
       "condition": "AND",
       "key": "source_id",
       "operator": "=",
       "value": "np02-coldbox.trigger.heartbeatmaker_ru0_link6"
      }
     ]
    }
   ]
  },
  {
   "title": "TPHeartbeatMaker sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "measurement": "dunedaq.trigger.faketpcreatorheartbeatmakerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tpset_sent_count\"), 1s) FROM \"dunedaq.trigger.faketpcreatorheartbeatmakerinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "tpset_sent_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      {
       "condition": "AND",
       "key": "source_id",
       "operator": "=",
       "value": "np02-coldbox.trigger.heartbeatmaker_ru0_link6"
      }
     ]
    }
   ]
  },
  {
   "title": "TP Zipper",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Received",
     "measurement": "dunedaq.trigger.triggerzipperinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"n_received\"), 1s) FROM \"dunedaq.trigger.triggerzipperinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "n_received" ], "type": "field" }
      ],
      [
       { "params": [ "n_sent" ], "type": "field" }
      ],
      [
       { "params": [ "n_tardy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.zip_4" }
     ]
    },
    {
     "alias": "Sent",
     "measurement": "dunedaq.trigger.triggerzipperinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"n_sent\"), 1s) FROM \"dunedaq.trigger.triggerzipperinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "n_received" ], "type": "field" }
      ],
      [
       { "params": [ "n_sent" ], "type": "field" }
      ],
      [
       { "params": [ "n_tardy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.zip_4" }
     ]
    },
    {
     "alias": "Tardy",
     "measurement": "dunedaq.trigger.triggerzipperinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"n_tardy\"), 1s) FROM \"dunedaq.trigger.triggerzipperinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "n_received" ], "type": "field" }
      ],
      [
       { "params": [ "n_sent" ], "type": "field" }
      ],
      [
       { "params": [ "n_tardy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.zip_4" }
     ]
    }
   ]
  },
  {
   "title": "TAM HorizontalMuons",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Received",
     "measurement": "dunedaq.trigger.triggergenericmakerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"received_count\"), 1s) FROM \"dunedaq.trigger.triggergenericmakerinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "received_count" ], "type": "field" }
      ],
      [
       { "params": [ "sent_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.tam_4" }
     ]
    },
    {
     "alias": "Sent",
     "measurement": "dunedaq.trigger.triggergenericmakerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"sent_count\"), 1s) FROM \"dunedaq.trigger.triggergenericmakerinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "received_count" ], "type": "field" }
      ],
      [
       { "params": [ "sent_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.tam_4" }
     ]
    }
   ]
  },
  {
   "title": "TCM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Received",
     "measurement": "dunedaq.trigger.triggergenericmakerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"received_count\"),1s) FROM \"dunedaq.trigger.triggergenericmakerinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "received_count" ], "type": "field" }
      ],
      [
       { "params": [ "sent_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.tcm" }
     ]
    },
    {
     "alias": "Sent",
     "measurement": "dunedaq.trigger.triggergenericmakerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"sent_count\"),1s) FROM \"dunedaq.trigger.triggergenericmakerinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "received_count" ], "type": "field" }
      ],
      [
       { "params": [ "sent_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.tcm" }
     ]
    }
   ]
  }
 ]
}