{
 "title": "Calibration Laser",
 "tags": [
  "v5.6.0",
  "Subsystem"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "session",
    "label": "Session",
    "query": {
     "query": "SELECT session FROM (SELECT num_control_messages_sent, session FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "SELECT application FROM (SELECT num_control_messages_sent, application FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter)"
    }
   },
   {
    "name": "DLH",
    "label": "Link handlers",
    "query": {
     "query": "SELECT \"element\" FROM (SELECT \"rate_payloads_consumed\", \"element\" FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$session",
     "query": "SELECT \"run_number\" FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"='${session}' AND $timeFilter AND run_number>0"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Configure state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT  last(\"hardware_configured\") FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter AND session='${session}' "
    }
   ]
  },
  {
   "title": "Running state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": " ",
     "query": "SELECT  last(hardware_running) FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter AND  session='${session}' "
    }
   ]
  },
  {
   "title": " Control Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 3 },
   "targets": [
    {
     "alias": "Sent to $tag_element",
     "query": "SELECT  last(num_control_messages_sent) FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter AND  session='${session}' AND application=~/${application}/ GROUP BY element, time($__interval) fill(null)  "
    },
    {
     "alias": "Responses from $tag_element",
     "query": "SELECT  last(num_control_responses_received) FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter AND  session='${session}' AND application=~/${application}/ GROUP BY element, time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Words in $tag_element",
     "query": "SELECT  mean(average_buffer_occupancy) FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter AND  session='${session}' AND application=~/${application}/ GROUP BY element, time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "HSI counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Total ",
     "query": "SELECT sum(partial) FROM (SELECT  last(num_total_triggers_received) AS partial FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter AND session='${session}' AND application=~/${application}/ GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval)"
    },
    {
     "alias": "partial for $tag_element ",
     "query": "SELECT  last(num_total_triggers_received) AS partial FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter AND session='${session}' AND application=~/${application}/ GROUP BY element, time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "HSI failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Failed in $tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.ctbmodules.opmon.CTBModuleInfo",
     "query": "SELECT non_negative_derivative(last(failed_to_send_hsi_events_counter), 1s) FROM \"dunedaq.cibmodules.opmon.CIBModuleInfo\" WHERE $timeFilter AND  session='${session}' AND application=~/${application}/ GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ts_word_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Data Handling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "HSI Handlers - receiving rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT mean(\"rate_payloads_consumed\")*1000 FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval), \"element\"",
     "select": [
      [
       { "params": [ "rate_payloads_consumed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers - Number of elements",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT mean(\"num_buffer_elements\") FROM \"dunedaq.datahandlinglibs.opmon.LatencyBufferInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval), \"element\" fill(null)",
     "select": [
      [
       { "params": [ "num_buffer_elements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT sum(\"data\") FROM ( SELECT mean(\"num_buffer_elements\") AS \"data\" FROM \"dunedaq.datahandlinglibs.opmon.LatencyBufferInfo\" WHERE  \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval), \"element\" fill(null) ) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "num_buffer_elements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers - Operational rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "alias": "Cleanups",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_buffer_cleanups\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_buffer_cleanups" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    },
    {
     "alias": "Overwritten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_payloads_overwritten\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/  AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "num_payloads_overwritten" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Request answering time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Partition average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT sum(\"tot_request_response_time\")/sum(\"num_requests_handled\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND \"num_requests_handled\">0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT sum(\"tot_request_response_time\")/sum(\"num_requests_handled\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND \"num_requests_handled\">0 AND $timeFilter GROUP BY \"element\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT min(\"min_request_response_time\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND \"num_requests_handled\">0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT max(\"max_request_response_time\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND \"num_requests_handled\">0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Waiting requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT sum(\"num_requests_waiting\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval), \"element\"",
     "select": [
      [
       { "params": [ "num_requests_waiting" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "alias": "Total ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Found",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_found\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_found" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Delayed ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_delayed\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_delayed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Bad ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_bad\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_bad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Old window",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_old_window\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Timing out ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_timed_out\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Uncategorized",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_uncategorized\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_uncategorized" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  { "title": "Single elements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Buffers - Operational rates for ${DLH}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "repeat": "DLH",
   "targets": [
    {
     "alias": "Cleanups",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_buffer_cleanups\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_buffer_cleanups" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    },
    {
     "alias": "Overwritten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_payloads_overwritten\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/  AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "num_payloads_overwritten" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rates for ${DLH}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "repeat": "DLH",
   "targets": [
    {
     "alias": "Total ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Found",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_found\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_found" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Delayed ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_delayed\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_delayed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Bad ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_bad\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_bad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Old window",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_old_window\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Timing out ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_timed_out\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Uncategorized",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_uncategorized\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${DLH}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_uncategorized" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  }
 ]
}