{
 "title": "Cosmic Ray Tagger",
 "tags": [
  "Subsystem",
  "v4.4.6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "query": "influxdb" },
   {
    "name": "partition",
    "label": "Partition",
    "query": "SHOW TAG VALUES WITH KEY=\"partition_id\" where $timeFilter "
   },
   {
    "name": "application",
    "label": "CRT App",
    "query": "SELECT \"source_id\" FROM  (SELECT \"bytes_from_file\", \"source_id\" FROM \"dunedaq.crtmodules.crtreaderinfo.Info\" WHERE \"partition_id\" = '${partition}' AND $timeFilter) "
   }
  ]
 },
 "panels": [
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data rate from backend files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.crtmodules.crtreaderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes_from_file\")), 1s) FROM \"dunedaq.crtmodules.crtreaderinfo.Info\" WHERE \"source_id\"=~/[^.]+\\.${application}\\.[^.]+/ AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_from_file" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dropped frames",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.crtmodules.crtreaderinfo.Info",
     "query": "SELECT last(\"frames_dropped\") FROM \"dunedaq.crtmodules.crtreaderinfo.Info\" WHERE \"source_id\"=~/[^.]+\\.${application}\\.[^.]+/ AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_from_file" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Missed syncs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.crtmodules.crtreaderinfo.Info",
     "query": "SELECT last(\"syncs_missed\") FROM \"dunedaq.crtmodules.crtreaderinfo.Info\" WHERE \"source_id\"=~/[^.]+\\.${application}\\.[^.]+/ AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_from_file" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frame rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Frame rate to readout for ${application}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "repeat": "application",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "CRT side",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.crtmodules.crtreaderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"frames_built\")), 1s) FROM \"dunedaq.crtmodules.crtreaderinfo.Info\" WHERE \"source_id\"=~/[^.]+\\.${application}\\.[^.]+/ AND  $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_from_file" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Readout side",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.crtmodules.crtreaderinfo.Info",
     "query": "SELECT mean(\"rate_payloads_consumed\")*1000 FROM \"dunedaq.readoutlibs.readoutinfo.ReadoutInfo\" WHERE (partition_id = '${partition}' AND \"source_id\" =~ /[^.]+\\.${application}\\.[^.]+/) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "bytes_from_file" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "($B-$A)/$A", "type": "math" }
   ]
  }
 ]
}