{
 "title": "DAQ overview",
 "tags": [
  "v5.7.0",
  "Main"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   { "name": "postgresql", "label": "PostgresSQL", "query": "grafana-postgresql-datasource" },
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT \"session\" FROM (SELECT \"state\",\"session\" FROM \"dunedaq.appfwk.opmon.AppInfo\" WHERE $timeFilter)"
   },
   {
    "name": "controller",
    "query": "SELECT \"application\" FROM (SELECT \"state\", \"application\" FROM \"dunedaq.drunc.opmon.FSMStatus\" WHERE $timeFilter AND session='$session')"
   },
   {
    "name": "data_writers",
    "query": "SELECT element FROM (SELECT \"element\", \"records_written\" FROM \"dunedaq.dfmodules.opmon.DataWriterInfo\" WHERE \"session\" = '${session}' AND $timeFilter )"
   },
   { "name": "last_moment", "query": "1m" }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$session",
     "query": "SELECT \"run_number\" FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"='${session}' AND $timeFilter AND run_number>0"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "query": "SELECT last(\"state\") FROM \"dunedaq.drunc.opmon.FSMStatus\" WHERE \"session\" = '${session}' AND application='${controller}' AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger" },
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" }
     ]
    }
   ]
  },
  {
   "title": "Substate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "query": "SELECT last(\"sub_state\") FROM \"dunedaq.drunc.opmon.FSMStatus\" WHERE \"session\" = '${session}' AND application='${controller}' AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger" },
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" }
     ]
    }
   ]
  },
  {
   "title": "FSM Error State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "query": "SELECT last(\"in_error\") FROM \"dunedaq.drunc.opmon.FSMStatus\" WHERE \"session\" = '${session}' AND application='${controller}' AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" },
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_trigger" }
     ]
    }
   ]
  },
  {
   "title": "Run Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.drunc.opmon.RunInfo",
     "query": "SELECT last(\"run_type\") FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE session='${session}' AND application='${controller}' AND $timeFilter ",
     "select": [
      [
       { "params": [ "run_type" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.rcif.runinfo.Info",
     "query": "SELECT last(\"run_time_since_start\") FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\" = '${session}' AND $timeFilter AND \"application\" = '${controller}' AND run_time_since_start>0",
     "select": [
      [
       { "params": [ "runtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" }
     ]
    }
   ]
  },
  {
   "title": "Run number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "dunedaq.rcif.runinfo.Info",
     "query": "SELECT last(\"run_number\") FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"='${session}' AND application='${controller}' AND $timeFilter AND run_number>0",
     "select": [
      [
       { "params": [ "runno" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" }
     ]
    }
   ]
  },
  {
   "title": "Trigger Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "query": "SELECT last(\"data\") FROM (SELECT non_negative_derivative(last(\"td_inhibited_count\"), 1s) AS \"data\" FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE session ='${session}' AND time > now() - 60s GROUP BY time(500ms) ) ",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" },
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_trigger" }
     ]
    }
   ]
  },
  {
   "title": "Sending triggers at",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT last(\"data\") FROM (SELECT non_negative_derivative(distinct(\"td_sent_count\"), 1s) AS \"data\" FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE session ='${session}' AND $timeFilter GROUP BY time(1s) ) ",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Issued triggers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT last(\"td_sent_count\") FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE session ='${session}' AND $timeFilter AND  time >= ${__to}ms - ${last_moment}",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Written TRs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT sum(\"data\") FROM (SELECT last(\"records_written\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.DataWriterInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${data_writers}/ AND  $timeFilter AND  time >= ${__to}ms - ${last_moment} GROUP BY \"element\" ) ",
     "select": [
      [
       { "params": [ "records_received" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Trigger Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Generated triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(distinct(\"td_total_count\"), 1s) FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE session ='${session}' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Sent triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(distinct(\"td_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE session ='${session}' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Completed TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"tokens_received\")), 1s) FROM  \"dunedaq.dfmodules.opmon.DFOInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "records_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    },
    {
     "alias": "Written TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_records_written\")), 1s) FROM \"dunedaq.dfmodules.opmon.DataWriterInfo\" WHERE \"session\" = '${session}' AND $timeFilter AND \"new_records_written\" > 0 GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "records_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    },
    {
     "alias": "Total count",
     "query": "SELECT mean(\"td_sent_count\") FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE session = '${session}' AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Trigger decision rates per type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datafloworchestratorinfo.TriggerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"received\")),1s) FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE (\"session\"::tag = '${session}') AND $timeFilter GROUP BY \"type\", time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id::tag", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Total Beam triggers",
     "query": "SELECT cumulative_sum(sum(\"received\")) FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE (\"session\"::tag = '${session}') AND $timeFilter AND type=~/^kCTBBeamChkv(HL|HxL|HLx|HxLx)$/ GROUP BY time($__interval)  fill(null)"
    },
    {
     "alias": "$tag_type Beam triggers",
     "query": "SELECT cumulative_sum(sum(\"received\")) FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE (\"session\"::tag = '${session}') AND $timeFilter AND type=~/^kCTBBeamChkv(HL|HxL|HLx|HxLx)$/ GROUP BY type, time($__interval)  fill(null)"
    }
   ]
  },
  {
   "title": "Message Reporting",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT severity,time/1000000 as time,application_name,message,issue_name,host_name\nFROM \"ERSstream\"\nWHERE session='${session}' AND time >= ${__from}*1000000 AND time <= ${__to}*1000000\nORDER BY -time\n"
    }
   ]
  },
  {
   "title": "CTB Beam triggers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Raw beam",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"count\")), 1s) FROM \"dunedaq.ctbmodules.opmon.TriggerInfo\" WHERE \"session\" = '${session}' AND trigger='LLT_1' AND $timeFilter  GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Prescaled beam",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"count\")), 1s) FROM \"dunedaq.ctbmodules.opmon.TriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter AND  \"trigger\"=~/HLT_(2|3|4|5)/  GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Off-spill cosmic",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"count\")), 1s) FROM \"dunedaq.ctbmodules.opmon.TriggerInfo\"  WHERE \"session\" = '${session}' AND $timeFilter AND \"trigger\"='HLT_8' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    { "expression": "$D/$F", "type": "math" }
   ]
  },
  {
   "title": "Data Writers Information",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_application - $tag_element ",
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_bytes_output\")), 1s) FROM \"dunedaq.dfmodules.opmon.HDF5DataStoreInfo\" WHERE session = '${session}' AND $timeFilter GROUP BY time($__interval), \"application\", \"element\"\nfill(null)",
     "select": [
      [
       { "params": [ "bytes_output" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "${partition}_dataflow.datawriter"
      }
     ]
    },
    {
     "alias": "Total",
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_bytes_output\")), 1s) FROM \"dunedaq.dfmodules.opmon.HDF5DataStoreInfo\" WHERE session = '${session}' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "bytes_output" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "${partition}_dataflow.datawriter"
      }
     ]
    }
   ]
  },
  {
   "title": "Active front-end streams",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "countAll" ] } },
   "targets": [
    {
     "alias": "$tag_element: $tag_subelement, Queue $tag_queue",
     "query": "SELECT count(data) as \"Recieving Data\" FROM (SELECT non_negative_derivative(last(\"packets_received\"), 1s) AS data FROM \"dunedaq.dpdklibs.opmon.QueueInfo\" WHERE session = '${session}' AND $timeFilter GROUP BY time($__interval), element, subelement, \"queue\" fill(null) ) WHERE data > 0 GROUP BY element, subelement, queue"
    },
    {
     "alias": "$tag_element: $tag_subelement, Queue $tag_queue",
     "query": "SELECT count(data) as \"Total\" FROM (SELECT non_negative_derivative(last(\"packets_received\"), 1s) AS data FROM \"dunedaq.dpdklibs.opmon.QueueInfo\" WHERE session = '${session}' AND $timeFilter GROUP BY time($__interval), element, subelement, \"queue\" fill(null) ) WHERE data > -1 GROUP BY element, subelement, queue"
    }
   ]
  }
 ]
}