{
 "title": "Dataflow",
 "description": "Dataflow dashboard",
 "tags": [
  "Subsystem",
  "v5.4.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT \"session\" FROM (SELECT \"state\",\"session\" FROM \"dunedaq.appfwk.opmon.AppInfo\" WHERE $timeFilter)"
   },
   {
    "name": "application",
    "label": "DF Application",
    "query": "SELECT \"application\" FROM (SELECT \"application\", \"generated_data_requests\" FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\"='${session}' AND $timeFilter)"
   },
   {
    "name": "readout",
    "label": "Readout Application",
    "query": "SELECT \"application\" FROM (SELECT \"application\", \"data_requests_received\" FROM \"dunedaq.dfmodules.opmon.FADataRequestsCounterInfo\" WHERE \"session\"='${session}' AND $timeFilter)"
   },
   { "name": "data_request", "query": "DataRequest" },
   { "name": "fragment", "query": "Fragment" }
  ]
 },
 "panels": [
  { "title": "DFO and high level metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DFO time - Decision thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Forwarding decision",
     "query": "SELECT sum(\"forwarding_decision\") / (sum(\"waiting_for_decision\")+sum(\"deciding_destination\") + sum(\"forwarding_decision\")) FROM \"dunedaq.dfmodules.opmon.DFOInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Assignment time",
     "query": "SELECT sum(\"deciding_destination\") / (sum(\"waiting_for_decision\")+sum(\"deciding_destination\") + sum(\"forwarding_decision\")) FROM \"dunedaq.dfmodules.opmon.DFOInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) "
    },
    {
     "alias": "Waiting for TD",
     "query": "SELECT sum(\"waiting_for_decision\") / (sum(\"waiting_for_decision\")+sum(\"deciding_destination\") + sum(\"forwarding_decision\")) FROM \"dunedaq.dfmodules.opmon.DFOInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) "
    }
   ]
  },
  {
   "title": "DFO time - Token thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Waiting for token",
     "query": "SELECT sum(\"waiting_for_token\") / (sum(\"waiting_for_token\")+sum(\"processing_token\")) FROM \"dunedaq.dfmodules.opmon.DFOInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) "
    },
    {
     "alias": "Processing token",
     "query": "SELECT sum(\"processing_token\") / (sum(\"waiting_for_token\")+sum(\"processing_token\")) FROM \"dunedaq.dfmodules.opmon.DFOInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) "
    }
   ]
  },
  {
   "title": "Estimated trigger capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.DFApplicationInfo",
     "query": "SELECT sum(\"capacity_rate\") FROM \"dunedaq.dfmodules.opmon.DFApplicationInfo\" WHERE session='${session}' AND subelement=~/.*_${application}/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_subelement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.DFApplicationInfo",
     "query": "SELECT sum(\"capacity_rate\") FROM \"dunedaq.dfmodules.opmon.DFApplicationInfo\" WHERE session='${session}' AND subelement=~/.*_${application}/ AND $timeFilter GROUP BY subelement, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TD Time to complete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Min",
     "query": "SELECT min(\"completion_time\") FROM \"dunedaq.dfmodules.opmon.TRCompleteInfo\" WHERE \"session\"='${session}' AND subelement=~/.*_${application}/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Max",
     "query": "SELECT max(\"completion_time\") FROM \"dunedaq.dfmodules.opmon.TRCompleteInfo\" WHERE \"session\"='${session}' AND subelement=~/.*_${application}/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "$tag_subelement",
     "query": "SELECT mean(\"completion_time\") FROM \"dunedaq.dfmodules.opmon.TRCompleteInfo\" WHERE \"session\"='${session}' AND subelement=~/.*_${application}/ AND $timeFilter GROUP BY subelement, time($__interval) fill(null)"
    },
    {
     "alias": "Average",
     "query": "SELECT mean(\"completion_time\") FROM \"dunedaq.dfmodules.opmon.TRCompleteInfo\" WHERE \"session\"='${session}' AND subelement=~/.*_${application}/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Input / Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "DFO received decisions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"decisions_received\")), 1s) FROM \"dunedaq.dfmodules.opmon.DFOInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "DFO sent decisions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"decisions_sent\")), 1s) FROM \"dunedaq.dfmodules.opmon.DFOInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Data requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"generated_data_requests\")), 1s) FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Generated Trigger Records",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"generated_trigger_records\")), 1s) FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Fragments received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"received_fragments\")), 1s) FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "TDs statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Data Request width",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data_request_width\") / sum(\"generated_data_requests\") * 16 FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter AND \"generated_data_requests\" > 0 GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "average_data_request_width" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Trigger decision width",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"trigger_decision_width\") / sum(\"received_trigger_decisions\") * 16 FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter AND \"received_trigger_decisions\" > 0 GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "average_data_request_width" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Data Requests per TD",
     "query": "SELECT mean(\"data\") FROM (SELECT (last(\"pending_fragments\") +  last(\"fragments_in_the_book\")) / last(\"pending_trigger_decisions\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND \"pending_trigger_decisions\" > 0 AND $timeFilter GROUP BY time($__interval), \"element\" fill(null) ) GROUP BY time($__interval)  fill(null)"
    }
   ]
  },
  {
   "title": "Pending data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Pending Trigger decisions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (SELECT mean(\"pending_trigger_decisions\") AS \"data\"  FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\"='${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY time($__interval), \"application\" fill(null) ) GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "Pending fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (SELECT mean(\"pending_fragments\") AS \"data\"  FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE \"session\"='${session}' AND  \"application\"=~/${application}/ AND $timeFilter GROUP BY time($__interval), \"application\" fill(null) ) GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "select tag value" }
     ]
    },
    { "expression": "$F/($E+$F)", "type": "math" }
   ]
  },
  {
   "title": "Event Builder Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Lost fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (\n  SELECT last(\"lost_fragments\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.TRBErrors\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null) \n) GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "lost_fragments" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Unexpected fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (\n  SELECT last(\"unexpected_fragments\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.TRBErrors\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null) \n) GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "unexpected_fragments" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Invalid requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (\n  SELECT last(\"invalid_requests\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.TRBErrors\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null) \n) GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "invalid_requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Duplicated TD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (\n  SELECT last(\"duplicated_trigger_ids\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.TRBErrors\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY \"appplication\", time($__interval) fill(null) \n) GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "duplicated_trigger_ids" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Timed out TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (\n  SELECT last(\"timed_out_trigger_records\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.TRBErrors\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null) \n) GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "timed_out_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Unexpected TDs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (\n  SELECT last(\"unexpected_trigger_decisions\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.TRBErrors\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null) \n) GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "unexpected_trigger_decisions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Abandoned TRs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data\") FROM (\n  SELECT last(\"abandoned_trigger_records\") AS \"data\" FROM \"dunedaq.dfmodules.opmon.TRBErrors\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null) \n) GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "abandoned_trigger_records" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  { "title": "DF applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pending TD waiting time",
   "type": "timeseries",
   "description": "Data will not be visualised if no TRs are in making at the time of querying. This is likely to happen in a condition of low trigger rate. So, no worries if it happens. ",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Minimum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.dfapplicationinfo.Info",
     "query": "SELECT min(\"min_time_since_assignment\") FROM \"dunedaq.dfmodules.opmon.DFApplicationInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~/.+_${application}/ AND $timeFilter AND \"outstanding_decisions\" > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "min_time_since_assignment" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Maximum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.dfapplicationinfo.Info",
     "query": "SELECT max(\"max_time_since_assignment\") FROM \"dunedaq.dfmodules.opmon.DFApplicationInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~/.+_${application}/  AND $timeFilter AND \"outstanding_decisions\" > 0 GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "max_time_since_assignment" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "$tag_subelement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.dfapplicationinfo.Info",
     "query": "SELECT sum(\"total_time_since_assignment\")/sum(\"outstanding_decisions\") FROM  \"dunedaq.dfmodules.opmon.DFApplicationInfo\"  WHERE \"session\" = '${session}' AND \"subelement\"=~/.+_${application}/  AND $timeFilter AND \"outstanding_decisions\" > 0 GROUP BY \"subelement\", time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "total_time_since_assignment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Partition average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.dfapplicationinfo.Info",
     "query": "SELECT sum(\"total_time_since_assignment\")/sum(\"outstanding_decisions\") FROM  \"dunedaq.dfmodules.opmon.DFApplicationInfo\"  WHERE \"session\" = '${session}' AND \"subelement\"=~/.+_${df_app}/  AND $timeFilter AND \"outstanding_decisions\" > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_time_since_assignment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda" }
     ]
    }
   ]
  },
  {
   "title": "TRB activity - fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT sum(\"fragment_processing_us\")/sum(\"received_fragments\") FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE received_fragments>0 AND session='${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TRB activity - Trigger decisions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT sum(\"td_processing_us\")/sum(\"received_trigger_decisions\") FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE received_trigger_decisions > 0 AND session='${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TR builder average completion time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT sum(\"data_waiting_time\") / sum(\"generated_trigger_records\")  FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE session='${session}' AND application=~/${application}/ AND $timeFilter GROUP BY application, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Partition average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT sum(\"data_waiting_time\") / sum(\"generated_trigger_records\")  FROM \"dunedaq.dfmodules.opmon.TRBInfo\" WHERE session='${session}' AND application=~/${application}/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TR Writing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"writing_time_us\") / sum(\"new_records_written\") FROM \"dunedaq.dfmodules.opmon.DataWriterInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter AND \"new_records_written\" > 0 GROUP BY time($__interval), \"element\" fill(null)",
     "select": [
      [
       {
        "params": [
         "average_millisecond_per_trigger"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Parition Average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"writing_time_us\") / sum(\"new_records_written\") FROM \"dunedaq.dfmodules.opmon.DataWriterInfo\" WHERE \"session\" = '${session}' AND \"application\"=~/${application}/ AND $timeFilter AND \"new_records_written\" > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "average_millisecond_per_trigger"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  { "title": "Fragment aggregators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Fragment Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "Emtpy fragment rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"fragments_empty\")), 1s)  FROM \"dunedaq.dfmodules.opmon.FAFragmentsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Incomplete fragment rates",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"fragments_incomplete\")), 1s)  FROM \"dunedaq.dfmodules.opmon.FAFragmentsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Invalid fragment rates",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT sum(\"data\") FROM (SELECT last(\"fragments_invalid\") AS \"data\"  FROM \"dunedaq.dfmodules.opmon.FAFragmentsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter )GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total error for $tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"fragments_empty\")), 1s) + non_negative_derivative(cumulative_sum(sum(\"fragments_invalid\")), 1s) + non_negative_derivative(cumulative_sum(sum(\"fragments_incomplete\")), 1s) FROM \"dunedaq.dfmodules.opmon.FAFragmentsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data requests time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_application average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT  mean(average_us) FROM \"dunedaq.dfmodules.opmon.FragmentAggregatorTimeInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND data='${data_request}' AND $timeFilter GROUP BY application, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT  min(min_us) FROM \"dunedaq.dfmodules.opmon.FragmentAggregatorTimeInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND data='${data_request}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT  max(max_us) FROM \"dunedaq.dfmodules.opmon.FragmentAggregatorTimeInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND data='${data_request}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "partition average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT  mean(average_us) FROM \"dunedaq.dfmodules.opmon.FragmentAggregatorTimeInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND data='${data_request}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "Total Received rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"fragments_received\")), 1s)  FROM \"dunedaq.dfmodules.opmon.FAFragmentsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Sent rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"fragments_processed\")), 1s)  FROM \"dunedaq.dfmodules.opmon.FAFragmentsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT sum(\"data\") FROM (SELECT last(\"fragments_failed\") AS \"data\"  FROM \"dunedaq.dfmodules.opmon.FAFragmentsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter )GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "Total Received rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"data_requests_received\")), 1s)  FROM \"dunedaq.dfmodules.opmon.FADataRequestsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Sent rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"data_requests_processed\")), 1s)  FROM \"dunedaq.dfmodules.opmon.FADataRequestsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT sum(\"data\") FROM (SELECT last(\"data_requests_failed\") AS \"data\"  FROM \"dunedaq.dfmodules.opmon.FADataRequestsCounterInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND $timeFilter )GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fragment time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_application average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT  mean(average_us) FROM \"dunedaq.dfmodules.opmon.FragmentAggregatorTimeInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND data='${fragment}' AND $timeFilter GROUP BY application, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT  min(min_us) FROM \"dunedaq.dfmodules.opmon.FragmentAggregatorTimeInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND data='${fragment}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT  max(max_us) FROM \"dunedaq.dfmodules.opmon.FragmentAggregatorTimeInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND data='${fragment}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "partition average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.opmon.TRBInfo",
     "query": "SELECT  mean(average_us) FROM \"dunedaq.dfmodules.opmon.FragmentAggregatorTimeInfo\" WHERE session='${session}' AND application=~/^${readout}$/ AND data='${fragment}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}