{
 "title": "Frontend Felix",
 "tags": [
  "Subsystem",
  "v5.3.0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "session",
    "label": "Partition name",
    "query": "SELECT \"session\" FROM (SELECT \"state\",\"session\" FROM \"dunedaq.appfwk.opmon.AppInfo\" WHERE $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Runs",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$session",
     "query": "SELECT \"run_number\" FROM \"dunedaq.rcif.opmon.RunInfo\" WHERE \"session\" = '${session}' AND \"run_number\" >0 AND $timeFilter"
    }
   ]
  },
  {
   "title": "FELIXs Links status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardcontrollerinfo.LinkInfo",
     "query": "SELECT last(\"aligned\") AS \"aligned\" FROM \"dunedaq.flxlibs.opmon.LinkInfo\" WHERE \"session\" = '${session}' AND $timeFilter AND \"enabled\"=true GROUP BY \"element\", \"device\", \"link\" ORDER BY DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "link_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "gio_test" }
     ]
    }
   ]
  },
  {
   "title": "Felix counters - Blocks with errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$tag_element $tag_subelement card: $tag_card $tag_logical_unit link: $tag_link $tag_tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_blocks_processed_with_error\") FROM \"dunedaq.flxlibs.opmon.CardReaderInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\", \"subelement\", \"card\", \"logical_unit\", \"link\", \"tag\" fill(null)",
     "select": [
      [
       {
        "params": [
         "num_chunks_processed_with_error"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "felix_test_ruflx0.flxcard_1.elink_0_1_2"
      }
     ]
    }
   ]
  },
  {
   "title": "Felix counters - Blocks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "$tag_element $tag_subelement card: $tag_card $tag_logical_unit link: $tag_link $tag_tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_blocks_processed\") FROM \"dunedaq.flxlibs.opmon.CardReaderInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\", \"subelement\", \"card\", \"logical_unit\", \"link\", \"tag\" fill(null)",
     "select": [
      [
       { "params": [ "num_chunks_processed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": ":{USER}_test_ruflx0.flxcard_1.elink_0_1_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Felix counters - Chunks with errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "$tag_element $tag_subelement card: $tag_card $tag_logical_unit link: $tag_link $tag_tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_chunks_processed_with_error\") FROM \"dunedaq.flxlibs.opmon.CardReaderInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\", \"subelement\", \"card\", \"logical_unit\", \"link\", \"tag\" fill(null)",
     "select": [
      [
       {
        "params": [
         "num_chunks_processed_with_error"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "felix_test_ruflx0.flxcard_1.elink_0_1_2"
      }
     ]
    },
    {
     "alias": "crc $tag_element $tag_subelement card: $tag_card $tag_logical_unit link: $tag_link $tag_tag ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_subchunk_crc_errors\") FROM \"dunedaq.flxlibs.opmon.CardReaderInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\", \"subelement\", \"card\", \"logical_unit\", \"link\", \"tag\" fill(null)",
     "select": [
      [
       {
        "params": [
         "num_chunks_processed_with_error"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "felix_test_ruflx0.flxcard_1.elink_0_1_2"
      }
     ]
    },
    {
     "alias": "trunc $tag_element $tag_subelement card: $tag_card $tag_logical_unit link: $tag_link $tag_tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_subchunk_trunc_errors\") FROM \"dunedaq.flxlibs.opmon.CardReaderInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\", \"subelement\", \"card\", \"logical_unit\", \"link\", \"tag\" fill(null)",
     "select": [
      [
       {
        "params": [
         "num_chunks_processed_with_error"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "felix_test_ruflx0.flxcard_1.elink_0_1_2"
      }
     ]
    }
   ]
  },
  {
   "title": "Felix counters - Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": "$tag_element $tag_subelement card: $tag_card $tag_logical_unit link: $tag_link $tag_tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_chunks_processed\") FROM \"dunedaq.flxlibs.opmon.CardReaderInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\", \"subelement\", \"card\", \"logical_unit\", \"link\", \"tag\" fill(null) ",
     "select": [
      [
       { "params": [ "num_chunks_processed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": ":{USER}_test_ruflx0.flxcard_1.elink_0_1_1"
      }
     ]
    }
   ]
  }
 ]
}