{
 "title": "Frontend Ethernet",
 "tags": [
  "Subsystem",
  "v5.2.0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT \"session\" FROM (SELECT \"state\",\"session\" FROM \"dunedaq.appfwk.opmon.AppInfo\" WHERE $timeFilter)"
   },
   {
    "name": "CRP",
    "label": "CRP Controller",
    "query": "SELECT \"application\" FROM  (SELECT \"sent_udp_count\", \"application\" FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND $timeFilter)"
   },
   {
    "name": "WIB",
    "label": "WIB",
    "query": "SELECT element FROM  (SELECT \"sent_udp_count\", \"element\" FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND $timeFilter)"
   },
   {
    "name": "detector",
    "label": "Detector",
    "query": "SELECT data FROM  (SELECT \"sent_udp_count\", detector AS \"data\" FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND $timeFilter)"
   },
   {
    "name": "crate",
    "label": "Crate",
    "query": "SELECT data FROM  (SELECT \"sent_udp_count\", crate AS \"data\" FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND  $timeFilter)"
   },
   {
    "name": "slot",
    "label": "Slot",
    "query": "SELECT data FROM  (SELECT \"sent_udp_count\", slot AS \"data\" FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND crate =~ /${crate}/ AND $timeFilter)"
   },
   {
    "name": "link",
    "label": "Link",
    "query": "SELECT link FROM  (SELECT \"sent_udp_count\", \"link\" FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND crate =~ /${crate}/ AND slot=~ /${slot}/ AND $timeFilter)"
   },
   {
    "name": "application",
    "label": "Readout Application",
    "query": "SELECT application FROM (SELECT \"ipackets\", \"application\" FROM \"dunedaq.dpdklibs.opmon.EthStats\" WHERE session = '${session}' AND $timeFilter )"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "SELECT queue FROM (SELECT \"packets_received\", \"queue\" FROM \"dunedaq.dpdklibs.opmon.QueueInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter )"
   },
   {
    "name": "DLH",
    "label": "DLH",
    "query": "SELECT element FROM (SELECT num_seq_id_errors, element FROM \"dunedaq.datahandlinglibs.opmon.FixedRateDataProcessorInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter )"
   }
  ]
 },
 "panels": [
  {
   "title": "Runs",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$session",
     "query": "SELECT \"run_number\" FROM \"dunedaq.rcif.opmon.RunInfo\" WHERE \"session\" = '${session}' AND \"run_number\" >0 AND $timeFilter"
    }
   ]
  },
  {
   "title": "Transmitters (Detector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UDP Sent rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "det: $tag_detector crt: $tag_crate slt: $tag_slot lnk: $tag_link",
     "query": "SELECT non_negative_derivative(last(\"sent_udp_count\"), 1s) FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND crate =~ /${crate}/ AND slot=~ /${slot}/ AND $timeFilter GROUP BY time($__interval), application, element, detector, crate, slot, link fill(null)"
    }
   ]
  },
  {
   "title": "Ping Sent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "det: $tag_detector crt: $tag_crate slt: $tag_slot lnk: $tag_link",
     "query": "SELECT non_negative_derivative(last(\"sent_ping_count\"),1s) FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND crate =~ /${crate}/ AND slot=~ /${slot}/ AND $timeFilter GROUP BY time($__interval), application, element, detector, crate, slot, link fill(null)"
    }
   ]
  },
  {
   "title": "UDP Received rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "det: $tag_detector crt: $tag_crate slt: $tag_slot lnk: $tag_link",
     "query": "SELECT non_negative_derivative(last(\"rcvd_udp_count\"), 1s) FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND crate =~ /${crate}/ AND slot=~ /${slot}/ AND $timeFilter GROUP BY time($__interval), application, element, detector, crate, slot, link fill(null)"
    }
   ]
  },
  {
   "title": "ARP Received",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "det: $tag_detector crt: $tag_crate slt: $tag_slot lnk: $tag_link",
     "query": "SELECT  non_negative_derivative(last(\"rcvd_arp_count\"), 1s)FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND crate =~ /${crate}/ AND slot=~ /${slot}/ AND $timeFilter GROUP BY time($__interval), application, element, detector, crate, slot, link fill(null)"
    }
   ]
  },
  {
   "title": "ARP Sent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "det: $tag_detector crt: $tag_crate slt: $tag_slot lnk: $tag_link",
     "query": "SELECT  non_negative_derivative(last(\"sent_arp_count\"), 1s) FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND crate =~ /${crate}/ AND slot=~ /${slot}/ AND $timeFilter GROUP BY time($__interval), application, element, detector, crate, slot, link fill(null)"
    }
   ]
  },
  {
   "title": "Ping Received",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "det: $tag_detector crt: $tag_crate slt: $tag_slot lnk: $tag_link",
     "query": "SELECT non_negative_derivative(last(\"rcvd_ping_count\"),1s) FROM \"dunedaq.hermesmodules.opmon.LinkInfo\" WHERE session = '${session}' AND application =~ /${CRP}/ AND element =~ /${WIB}/ AND detector =~ /${detector}/ AND crate =~ /${crate}/ AND slot=~ /${slot}/ AND $timeFilter GROUP BY time($__interval), application, element, detector, crate, slot, link fill(null)"
    }
   ]
  },
  { "title": "Receiver (NIC Stats)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Input Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"ipackets\")), 1s) FROM  \"dunedaq.dpdklibs.opmon.EthStats\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"ibytes\")), 1s) FROM  \"dunedaq.dpdklibs.opmon.EthStats\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null) "
    }
   ]
  },
  {
   "title": "Output Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"opackets\")), 1s) FROM  \"dunedaq.dpdklibs.opmon.EthStats\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null) "
    }
   ]
  },
  {
   "title": "Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"obytes\")), 1s) FROM  \"dunedaq.dpdklibs.opmon.EthStats\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "Input Missed Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"imissed\")), 1s) FROM  \"dunedaq.dpdklibs.opmon.EthStats\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "Input Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"ierrors\")), 1s) FROM  \"dunedaq.dpdklibs.opmon.EthStats\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "Output Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"oerrors\")), 1s) FROM  \"dunedaq.dpdklibs.opmon.EthStats\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "Rx No MBufs Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_nombuf\")), 1s) FROM  \"dunedaq.dpdklibs.opmon.EthStats\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  { "title": "Receiver (NIC XStats)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Received Good Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_good_packets\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsInfo\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "RX Good Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_good_bytes\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsInfo\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "RX Jumbo Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_size_1523_to_max_packets\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsInfo\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null) "
    }
   ]
  },
  {
   "title": "RX Queue Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element - $tag_queue",
     "query": "SELECT sum(\"packets\") FROM \"dunedaq.dpdklibs.opmon.QueueEthXStats\" WHERE session = '${session}' AND application=~/${application}/ AND queue=~/rx-${queue}/ AND $timeFilter GROUP BY element, queue, time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "RX Queue Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element - $tag_queue",
     "query": "SELECT sum(\"errors\") FROM \"dunedaq.dpdklibs.opmon.QueueEthXStats\" WHERE session = '${session}' AND application=~/${application}/ AND queue=~/rx-${queue}/ AND $timeFilter GROUP BY element, queue, time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "RX Queue bytes errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element - $tag_queue",
     "query": "SELECT sum(\"bytes\") FROM \"dunedaq.dpdklibs.opmon.QueueEthXStats\" WHERE session = '${session}' AND application=~/${application}/ AND queue=~/rx-${queue}/ AND $timeFilter GROUP BY element, queue, time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "RX Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_dropped_packets\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsInfo\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "RX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_errors\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsErrors\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "RX CRC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_crc_errors\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsErrors\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "RX Illegal Byte Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_illegal_byte_errors\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsErrors\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "RX Missed Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_missed_errors\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsErrors\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null)"
    }
   ]
  },
  {
   "title": "RX Jabber Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"rx_jabber_errors\")), 1s) FROM \"dunedaq.dpdklibs.opmon.EthXStatsErrors\"  WHERE session = '${session}' AND application =~ /${application}/ AND $timeFilter GROUP BY time($__interval), element fill(null) "
    }
   ]
  },
  { "title": "DPDK Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "RX UDP Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_application - $tag_queue",
     "query": "SELECT non_negative_derivative(last(\"packets_received\"), 1s) FROM \"dunedaq.dpdklibs.opmon.QueueInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND queue =~ /${queue}/ AND $timeFilter GROUP BY time($__interval), application, \"queue\" fill(null)"
    }
   ]
  },
  {
   "title": "RX UDP Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_application - $tag_queue",
     "query": "SELECT non_negative_derivative(last(\"bytes_received\"), 1s) FROM \"dunedaq.dpdklibs.opmon.QueueInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND queue =~ /${queue}/ AND $timeFilter GROUP BY time($__interval), application, \"queue\" fill(null)"
    }
   ]
  },
  {
   "title": "RX Full Bursts Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_application - $tag_queue",
     "query": "SELECT non_negative_derivative(last(\"full_rx_burst\"), 1s) FROM \"dunedaq.dpdklibs.opmon.QueueInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND queue =~ /${queue}/ AND $timeFilter GROUP BY time($__interval), application, \"queue\" fill(null)"
    }
   ]
  },
  {
   "title": "RX Bursts Max Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    {
     "alias": "$tag_application - $tag_queue",
     "query": "SELECT mean(\"max_burst_size\") FROM \"dunedaq.dpdklibs.opmon.QueueInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND queue =~ /${queue}/ AND $timeFilter GROUP BY time($__interval), application, \"queue\" fill(null) "
    }
   ]
  },
  {
   "title": "RX Dropped Frames rate for ${application}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "repeat": "application",
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_subelement",
     "query": "SELECT non_negative_derivative(last(\"dropped_frames\"), 1s) FROM \"dunedaq.dpdklibs.opmon.SourceInfo\" WHERE session = '${session}' AND application=~/${application}/ AND $timeFilter GROUP BY time($__interval), \"subelement\" fill(null)"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sequence ID errors at DLH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT non_negative_derivative(last(\"num_seq_id_errors\"), 1s) FROM \"dunedaq.datahandlinglibs.opmon.FixedRateDataProcessorInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND element =~ /${DLH}/ AND $timeFilter GROUP BY time($__interval), \"element\" fill(null)"
    }
   ]
  },
  {
   "title": "Timestamp Errors at DLH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT non_negative_derivative(last(\"num_ts_errors\"), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.FixedRateDataProcessorInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND element =~ /${DLH}/ AND $timeFilter GROUP BY time($__interval), \"element\" fill(null)"
    }
   ]
  },
  {
   "title": "Min Sequence ID jump at DLH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT min(\"min_seq_id_jump\")  FROM \"dunedaq.datahandlinglibs.opmon.FixedRateDataProcessorInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND element =~ /${DLH}/ AND $timeFilter GROUP BY time($__interval), \"element\" fill(null)"
    }
   ]
  },
  {
   "title": "Max Sequence ID jump at DLH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT max(\"max_seq_id_jump\")  FROM \"dunedaq.datahandlinglibs.opmon.FixedRateDataProcessorInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND element =~ /${DLH}/ AND $timeFilter GROUP BY time($__interval), \"element\" fill(null)"
    }
   ]
  },
  {
   "title": "Total errors at DLH for ${application}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "repeat": "application",
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(last(\"num_seq_id_errors\"), 1s) + non_negative_derivative(last(\"num_ts_errors\"), 1s) FROM \"dunedaq.datahandlinglibs.opmon.FixedRateDataProcessorInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND element =~ /${DLH}/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Min/Max Sequence ID jump at DLH for application ${application}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "repeat": "application",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Max",
     "query": "SELECT max(\"max_seq_id_jump\")  FROM \"dunedaq.datahandlinglibs.opmon.FixedRateDataProcessorInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND element =~ /${DLH}/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Min",
     "query": "SELECT min(\"min_seq_id_jump\") FROM \"dunedaq.datahandlinglibs.opmon.FixedRateDataProcessorInfo\" WHERE session = '${session}' AND application =~ /${application}/ AND element =~ /${DLH}/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}