{
 "title": "FSM status",
 "tags": [
  "Subsystem",
  "v5.4.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influx", "query": "influxdb" },
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT \"session\" FROM (SELECT \"state\", \"session\" FROM \"dunedaq.drunc.opmon.FSMStatus\" WHERE $timeFilter)"
   },
   {
    "name": "controller",
    "label": "Controllers",
    "query": "SELECT \"application\" FROM (SELECT \"state\", \"application\" FROM \"dunedaq.drunc.opmon.FSMStatus\" WHERE $timeFilter AND session='$session')"
   },
   {
    "name": "command",
    "label": "Commands",
    "query": "SELECT \"Command\" FROM (SELECT \"execution_time_ns\", \"Command\" FROM \"dunedaq.drunc.opmon.CommandTime\" WHERE $timeFilter AND session='$session')"
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmon.RunInfo",
     "query": "SELECT last(\"run_number\") FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"='${session}' AND $timeFilter AND run_number>0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.opmon.RunInfo",
     "query": "SELECT last(\"run_type\")  FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"::tag ='${session}' AND $timeFilter AND \"application\"::tag = 'root-controller'",
     "select": [
      [
       { "params": [ "run_type" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Run Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"run_time_since_start\") FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\" = '${session}' AND $timeFilter AND \"application\" = 'root-controller' AND run_time_since_start>0"
    }
   ]
  },
  {
   "title": "Disable Data Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.opmon.RunInfo",
     "query": "SELECT last(\"disable_data_storage\") FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"::tag = '${session}' AND $timeFilter",
     "select": [
      [
       { "params": [ "disable_data_storage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "User requested trigger rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "measurement": "dunedaq.opmon.RunInfo",
     "query": "SELECT mean(\"trigger_rate\") FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"::tag = '${session}' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "trigger_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FSM State",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "application::tag" ], "type": "tag" }
     ],
     "measurement": "dunedaq.opmon.Status",
     "query": "SELECT last(\"state\") AS \"State\", \"sub_state\" AS \"Substate\", \"in_error\" AS \"In error\", \"included\" AS \"Included\" FROM \"dunedaq.drunc.opmon.FSMStatus\" WHERE \"session\" = '$session' GROUP BY \"application\"::tag ORDER BY time DESC ",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "sub_state" ], "type": "field" }
      ],
      [
       { "params": [ "in_error" ], "type": "field" }
      ],
      [
       { "params": [ "included" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Execution time for ${command}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "repeat": "command",
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "Command::tag" ], "type": "tag" }
     ],
     "measurement": "dunedaq.drunc.opmon.CommandTime",
     "query": "SELECT \"execution_time_ns\" FROM \"dunedaq.drunc.opmon.CommandTime\" WHERE session='${session}' AND \"Command\"=~/${command}/ AND $timeFilter GROUP BY \"application\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "execution_time_ns" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Command rate for ${command}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "repeat": "command",
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "Command::tag" ], "type": "tag" }
     ],
     "measurement": "dunedaq.drunc.opmon.CommandTime",
     "query": "SELECT non_negative_derivative(cumulative_sum(count(\"execution_time_ns\")), 1s) FROM \"dunedaq.drunc.opmon.CommandTime\" WHERE session='${session}' AND \"Command\"=~/${command}/ AND $timeFilter GROUP BY \"application\", time($__interval) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "execution_time_ns" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}