{
 "title": "Monitoring",
 "tags": [
  "v5.3.3",
  "Subsystem"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT \"session\" FROM (SELECT \"state\",\"session\" FROM \"dunedaq.appfwk.opmon.AppInfo\" WHERE $timeFilter)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "SELECT \"application\" FROM (SELECT \"application\",\"n_published_measurements\" FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"='${session}' AND $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Publishing rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"n_published_measurements\")), 1s) FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Publishing nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT mean(\"n_publishing_nodes\") FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Publishing rate per node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT  non_negative_derivative(cumulative_sum(sum(\"n_published_measurements\")), 1s)  / mean(\"n_publishing_nodes\") FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Publishing time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT mean(\"clockwall_elapsed_time_us\") FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Publishing time per node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT mean(\"clockwall_elapsed_time_us\")/mean(\"n_publishing_nodes\") FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE  \"n_publishing_nodes\" > 0 AND \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Publishing time per measurements",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT mean(\"cpu_elapsed_time_us\")/mean(\"n_published_measurements\") FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE  \"n_publishing_nodes\" > 0 AND \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Ignored publishing rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"n_ignored_measurements\")), 1s) FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Publishing error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"n_errors\")), 1s) FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Link dropping rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"n_invalid_links\")), 1s) FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  },
  {
   "title": "Non Publishing nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.opmonlib.opmon.MonitoringTreeInfo",
     "query": "SELECT mean(\"n_registered_nodes\") - mean(\"n_publishing_nodes\")  FROM \"dunedaq.opmonlib.opmon.MonitoringTreeInfo\" WHERE \"session\"::tag ='${session}' AND \"application\"::tag=~/${application}/ AND $timeFilter GROUP BY \"application\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_published_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=~", "value": "/^$session$/" }
     ]
    }
   ]
  }
 ]
}