{
 "title": "Network Manager",
 "tags": [
  "v5.3.3",
  "Subsystem"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT \"session\" FROM (SELECT \"state\",\"session\" FROM \"dunedaq.appfwk.opmon.AppInfo\" WHERE $timeFilter)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "SELECT \"application\" FROM (SELECT \"messages\", \"application\" FROM \"dunedaq.ipm.opmon.SenderInfo\",\"dunedaq.ipm.opmon.SenderInfo\"  WHERE \"session\"='${session}' AND $timeFilter)"
   },
   {
    "name": "connection",
    "label": "Connection",
    "query": "SELECT \"subelement\" FROM (SELECT \"messages\", \"subelement\" FROM \"dunedaq.ipm.opmon.SenderInfo\",\"dunedaq.ipm.opmon.SenderInfo\"  WHERE \"session\"='${session}' AND \"application\"=~/${application}/ AND $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_subelement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes\")), 1s) FROM \"dunedaq.ipm.opmon.SenderInfo\" WHERE \"session\" = '${session}' AND \"subelement\" =~ /${connection}/ AND $timeFilter GROUP BY time($__interval), \"subelement\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_subelement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes\")), 1s) FROM \"dunedaq.ipm.opmon.ReceiverInfo\" WHERE \"session\" = '${session}' AND \"subelement\" =~ /${connection}/ AND $timeFilter GROUP BY time($__interval), \"subelement\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Average message size - sender side",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_subelement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT sum(\"bytes\") / sum(\"messages\") FROM \"dunedaq.ipm.opmon.SenderInfo\" WHERE \"session\" = '${session}' AND \"subelement\" =~ /${connection}/ AND $timeFilter GROUP BY time($__interval), \"subelement\"",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Sent Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_subelement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"messages\")), 1s) FROM \"dunedaq.ipm.opmon.SenderInfo\" WHERE \"session\" = '${session}' AND \"subelement\" =~ /${connection}/ AND $timeFilter GROUP BY time($__interval), \"subelement\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_subelement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"messages\")), 1s) FROM \"dunedaq.ipm.opmon.ReceiverInfo\" WHERE \"session\" = '${session}' AND \"subelement\" =~ /${connection}/ AND $timeFilter GROUP BY time($__interval), \"subelement\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Average message size - received side",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_subelement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT sum(\"bytes\") / sum(\"messages\") FROM \"dunedaq.ipm.opmon.ReceiverInfo\" WHERE \"session\" = '${session}' AND \"subelement\" =~ /${connection}/ AND $timeFilter GROUP BY time($__interval), \"subelement\"",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Application monitors - bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${application} bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
     "repeat": "application",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "To $tag_subelement",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "dunedaq.appfwk.queueinfo.Info",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes\")), 1s) FROM \"dunedaq.ipm.opmon.SenderInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~ /${connection}/ AND $timeFilter AND \"messages\">0 GROUP BY time($__interval), \"subelement\"",
       "select": [
        [
         { "params": [ "number_of_elements" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " * 100" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_dataflow.trigger_record_q"
        }
       ]
      },
      {
       "alias": "From $tag_subelement",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "dunedaq.appfwk.queueinfo.Info",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes\")), 1s) FROM \"dunedaq.ipm.opmon.ReceiverInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~ /${connection}/ AND $timeFilter AND \"messages\">0 GROUP BY time($__interval), \"subelement\"",
       "select": [
        [
         { "params": [ "number_of_elements" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " * 100" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_dataflow.trigger_record_q"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Application monitors - messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${application} messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
     "repeat": "application",
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "alias": "To $tag_subelement",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "dunedaq.appfwk.queueinfo.Info",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes\")), 1s) FROM \"dunedaq.ipm.opmon.SenderInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~ /${connection}/ AND $timeFilter AND \"messages\">0 GROUP BY time($__interval), \"subelement\"",
       "select": [
        [
         { "params": [ "number_of_elements" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " * 100" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_dataflow.trigger_record_q"
        }
       ]
      },
      {
       "alias": "From $tag_subelement",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "dunedaq.appfwk.queueinfo.Info",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes\")), 1s) FROM \"dunedaq.ipm.opmon.ReceiverInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~ /${connection}/ AND $timeFilter AND \"messages\">0 GROUP BY time($__interval), \"subelement\"",
       "select": [
        [
         { "params": [ "number_of_elements" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " * 100" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_dataflow.trigger_record_q"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Balance - bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Balance for ${connection}",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "repeat": "connection",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "Out of $tag_application",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "dunedaq.appfwk.queueinfo.Info",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes\")), 1s) FROM \"dunedaq.ipm.opmon.SenderInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~ /${connection}/ AND \"application\" =~ /${application}/ AND $timeFilter AND \"messages\">0 GROUP BY time($__interval), \"application\"",
       "select": [
        [
         { "params": [ "number_of_elements" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " * 100" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_dataflow.trigger_record_q"
        }
       ]
      },
      {
       "alias": "Into $tag_application",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "dunedaq.appfwk.queueinfo.Info",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"bytes\")), 1s) FROM \"dunedaq.ipm.opmon.ReceiverInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~ /${connection}/ AND \"application\" =~ /${application}/ AND $timeFilter AND \"messages\">0 GROUP BY time($__interval), \"application\"",
       "select": [
        [
         { "params": [ "number_of_elements" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " * 100" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_dataflow.trigger_record_q"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Balance - messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Balance for ${connection}",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "repeat": "connection",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "Out of $tag_application",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "dunedaq.appfwk.queueinfo.Info",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"messages\")), 1s) FROM \"dunedaq.ipm.opmon.SenderInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~ /${connection}/ AND \"application\" =~ /${application}/ AND $timeFilter AND \"messages\">0 GROUP BY time($__interval), \"application\"",
       "select": [
        [
         { "params": [ "number_of_elements" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " * 100" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_dataflow.trigger_record_q"
        }
       ]
      },
      {
       "alias": "Into $tag_application",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "dunedaq.appfwk.queueinfo.Info",
       "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"messages\")), 1s) FROM \"dunedaq.ipm.opmon.ReceiverInfo\" WHERE \"session\" = '${session}' AND \"subelement\"=~ /${connection}/ AND \"application\" =~ /${application}/ AND $timeFilter AND \"messages\">0 GROUP BY time($__interval), \"application\"",
       "select": [
        [
         { "params": [ "number_of_elements" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         { "params": [ " * 100" ], "type": "math" }
        ]
       ],
       "tags": [
        {
         "key": "source_id",
         "operator": "=",
         "value": "maroda_test_dataflow.trigger_record_q"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}