{
 "title": "Old Frontend Ethernet",
 "tags": [
  "Subsystem",
  "v4.1.0"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SHOW TAG VALUES WITH KEY=\"partition_id\" where $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Received total packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT sum(\"total_packets\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Packet rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT mean(\"packets_per_second\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Byte rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT mean(\"packets_per_second\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Max Bad TS devation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT max(\"max_bad_ts_deviation\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Bad TS packet rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT mean(\"bad_ts_packets_per_second\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Bad size packet rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT mean(\"bad_size_packets_per_second\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Max Bad Seq ID deviation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT max(\"max_bad_seq_id_deviation\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Bad Sequence ID packet rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT mean(\"bad_seq_id_packets_per_second\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Max packet size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT max(\"max_packet_size\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Min packet size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "query": "SELECT max(\"min_packet_size\") FROM \"dunedaq.dpdklibs.receiverinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)"
    }
   ]
  }
 ]
}