{
 "title": "Photon Detection System",
 "tags": [
  "Subsystem",
  "v5.5.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT \"session\" FROM (SELECT \"state\",\"session\" FROM \"dunedaq.appfwk.opmon.AppInfo\" WHERE $timeFilter)"
   },
   {
    "name": "application",
    "label": "Application name",
    "query": "SELECT \"application\" FROM (SELECT \"application\",\"total_packets\" FROM  \"dunedaq.daphnemodules.opmon.StreamInfo\" WHERE $timeFilter AND \"session\"='${session}' )   "
   },
   {
    "name": "daphne",
    "label": "Daphne",
    "query": "SELECT \"element\" FROM (SELECT \"element\",\"total_packets\" FROM  \"dunedaq.daphnemodules.opmon.StreamInfo\" WHERE $timeFilter AND \"session\"='${session}' AND \"application\"=~/${application}/ )   "
   },
   {
    "name": "channel",
    "label": "Channel",
    "query": "SELECT \"channel\" FROM (SELECT \"channel\",\"total_packets\" FROM  \"dunedaq.daphnemodules.opmon.ChannelInfo\" WHERE $timeFilter AND \"session\"='${session}' AND \"application\"=~/${application}/ AND \"element\"=~/${daphne}/ )   "
   }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$session",
     "query": "SELECT \"run_number\" FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"='${session}' AND $timeFilter AND run_number>0"
    }
   ]
  },
  { "title": "Mezzanine metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Thresholds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Daphne $tag_element, ch $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.daphnemodules.opmon.TempTriggerSnapshotInfo",
     "query": "SELECT mean(\"threshold\") FROM \"dunedaq.daphnemodules.opmon.TempTriggerSnapshotInfo\" WHERE (\"session\"::tag = '${session}') AND $timeFilter GROUP BY element, channel, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "threshold" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=", "value": "maroda" }
     ]
    }
   ]
  },
  {
   "title": "Records",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "Daphne $tag_element, ch $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.daphnemodules.opmon.TempTriggerSnapshotInfo",
     "query": "SELECT non_negative_derivative(last(\"record_count\"), 1s) FROM \"dunedaq.daphnemodules.opmon.TempTriggerSnapshotInfo\" WHERE (\"session\"::tag = '${session}') AND $timeFilter GROUP BY element, channel, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "threshold" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=", "value": "maroda" }
     ]
    }
   ]
  },
  {
   "title": "Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "Daphne $tag_element, ch $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.daphnemodules.opmon.TempTriggerSnapshotInfo",
     "query": "SELECT non_negative_derivative(last(\"busy_count\"), 1s) FROM \"dunedaq.daphnemodules.opmon.TempTriggerSnapshotInfo\" WHERE (\"session\"::tag = '${session}') AND $timeFilter GROUP BY element, channel, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "threshold" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=", "value": "maroda" }
     ]
    }
   ]
  },
  {
   "title": "Full",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "Daphne $tag_element, ch $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.daphnemodules.opmon.TempTriggerSnapshotInfo",
     "query": "SELECT non_negative_derivative(last(\"full_count\"), 1s) FROM \"dunedaq.daphnemodules.opmon.TempTriggerSnapshotInfo\" WHERE (\"session\"::tag = '${session}') AND $timeFilter GROUP BY element, channel, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "threshold" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "session::tag", "operator": "=", "value": "maroda" }
     ]
    }
   ]
  },
  { "title": "Data rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Packages to Felix rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Rate $tag_element",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_packets\")), 1s)  FROM \"dunedaq.daphnemodules.opmon.StreamInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${daphne}/ AND $timeFilter GROUP BY time($__interval), \"element\""
    }
   ]
  },
  {
   "title": "Data in FIFO from ${daphne}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "repeat": "daphne",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "ch $tag_channel",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_packets\")), 1s)  FROM \"dunedaq.daphnemodules.opmon.ChannelInfo\" WHERE \"session\" = '${session}' AND \"element\"=~ /${daphne}/ AND \"channel\"=~/${channel}/ AND $timeFilter GROUP BY time($__interval), \"channel\""
    }
   ]
  },
  {
   "title": "Selftriggers from ${daphne}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "repeat": "daphne",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "ch $tag_channel",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_triggers\")), 1s) FROM \"dunedaq.daphnemodules.opmon.ChannelInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${daphne}/ AND \"channel\"=~/${channel}/ AND $timeFilter GROUP BY time($__interval), \"channel\""
    }
   ]
  },
  {
   "title": "Data to Felix rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Rate $tag_element",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_packets\")), 1s) *1864 FROM  \"dunedaq.daphnemodules.opmon.StreamInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${daphne}/ AND $timeFilter GROUP BY time($__interval), \"element\""
    },
    {
     "alias": "Total",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_packets\")), 1s) *1864 FROM  \"dunedaq.daphnemodules.opmon.StreamInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${daphne}/ AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Packages Dropped - rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"new_dropped_packets\")), 1s)  FROM \"dunedaq.daphnemodules.opmon.StreamInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${daphne}/ AND $timeFilter GROUP BY time($__interval), \"element\""
    }
   ]
  },
  {
   "title": "Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data to Felix",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_element",
       "query": "SELECT last(\"total_packets\") FROM \"dunedaq.daphnemodules.opmon.StreamInfo\"  WHERE \"session\" = '${session}' AND \"element\"=~/${daphne}/ AND $timeFilter GROUP BY time($__interval), \"element\" "
      }
     ]
    },
    {
     "title": "Data in FIFO from ${daphne}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 68 },
     "repeat": "daphne",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_channel",
       "query": "SELECT last(\"total_packets\") FROM \"dunedaq.daphnemodules.opmon.ChannelInfo\" WHERE \"session\" = '${session}' AND \"element\"=~ /${daphne}/ AND \"channel\"=~/${channel}/ AND $timeFilter GROUP BY time($__interval), \"channel\""
      }
     ]
    },
    {
     "title": "Selftriggers from ${daphne}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 68 },
     "repeat": "daphne",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_channel",
       "query": "SELECT last(\"total_triggers\") FROM \"dunedaq.daphnemodules.opmon.ChannelInfo\" WHERE \"session\" = '${session}' AND \"element\"=~ /${daphne}/ AND \"channel\"=~/${channel}/ AND $timeFilter GROUP BY time($__interval), \"channel\""
      }
     ]
    }
   ]
  },
  { "title": "Bias", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Bias for ${daphne}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "repeat": "daphne",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "AFE 0 ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"v_bias_0\")  FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND \"element\"=~ /${daphne}/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    },
    {
     "alias": "AFE 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"v_bias_1\") FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND \"element\"=~ /${daphne}/ AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    },
    {
     "alias": "AFE 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"v_bias_2\")  FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND \"element\"=~ /${daphne}/ AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    },
    {
     "alias": "AFE 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"v_bias_3\") FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND \"element\"=~ /${daphne}/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    },
    {
     "alias": "AFE 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"v_bias_4\")  FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND \"element\"=~ /${daphne}/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Power CE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"power_ce\")  FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    }
   ]
  },
  {
   "title": "Power (+2.5V)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"power_plus2p5v\")  FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    }
   ]
  },
  {
   "title": "Power (-5V)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"power_minus5v\")  FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT mean(\"temperature\")  FROM \"dunedaq.daphnemodules.opmon.GeneralInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval), \"element\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    }
   ]
  }
 ]
}