{
 "title": "Process Management",
 "tags": [
  "v5.7.0",
  "Global"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influx", "query": "influxdb" },
   {
    "name": "user",
    "query": "SELECT \"session\" FROM (SELECT \"n_running\", \"session\" FROM \"dunedaq.drunc.opmon.ProcessStatus\" WHERE $timeFilter)"
   },
   {
    "name": "sessions",
    "label": "Sessions",
    "query": {
     "query": "SELECT distinct(\"drunc_session\") FROM ( SELECT \"n_running\", \"drunc_session\" FROM \"dunedaq.drunc.opmon.ProcessStatus\" WHERE $timeFilter )"
    }
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Session",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Total",
     "measurement": "dunedaq.drunc.opmon.ProcessStatus",
     "query": "SELECT sum(\"n_session\")\nFROM (SELECT last(\"n_session\") AS \"n_session\" FROM \"dunedaq.drunc.opmon.ProcessStatus\" WHERE $timeFilter GROUP BY time($__interval), \"drunc_session\" ) \nGROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "n_session" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running processes",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_drunc_session",
     "measurement": "dunedaq.drunc.opmon.ProcessStatus",
     "query": "SELECT last(\"n_running\") AS \"n\"\nFROM \"dunedaq.drunc.opmon.ProcessStatus\"\nWHERE $timeFilter AND \"drunc_session\"=~/${sessions}/\nGROUP BY time($__interval), \"drunc_session\"",
     "select": [
      [
       { "params": [ "n_running" ], "type": "field" }
      ],
      [
       { "params": [ "n_dead" ], "type": "field" }
      ]
     ]
    },
    { "expression": "$B-$C", "type": "math" },
    {
     "alias": "Total",
     "measurement": "dunedaq.drunc.opmon.ProcessStatus",
     "query": "SELECT sum(\"n\")\nFROM ( SELECT last(\"n_running\") AS \"n\" FROM \"dunedaq.drunc.opmon.ProcessStatus\" WHERE $timeFilter GROUP BY \"drunc_session\" )\nGROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "n_running" ], "type": "field" }
      ],
      [
       { "params": [ "n_dead" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dead processes",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_drunc_session",
     "measurement": "dunedaq.drunc.opmon.ProcessStatus",
     "query": "SELECT last(\"n_dead\") AS \"n\"\nFROM \"dunedaq.drunc.opmon.ProcessStatus\"\nWHERE $timeFilter AND \"drunc_session\"=~/${sessions}/\nGROUP BY time($__interval), \"drunc_session\"",
     "select": [
      [
       { "params": [ "n_running" ], "type": "field" }
      ],
      [
       { "params": [ "n_dead" ], "type": "field" }
      ]
     ]
    },
    { "expression": "$B-$C", "type": "math" },
    {
     "alias": "Total",
     "measurement": "dunedaq.drunc.opmon.ProcessStatus",
     "query": "SELECT sum(\"n\")\nFROM ( SELECT last(\"n_dead\") AS \"n\" FROM \"dunedaq.drunc.opmon.ProcessStatus\" WHERE $timeFilter GROUP BY \"drunc_session\" )\nGROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "n_running" ], "type": "field" }
      ],
      [
       { "params": [ "n_dead" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}