{
 "title": "Timing",
 "tags": [
  "v5.3.1",
  "Global"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   { "name": "postgresql", "label": "PostgresSQL", "query": "postgres" },
   {
    "name": "partition",
    "label": "Partition",
    "query": "SHOW TAG VALUES FROM \"dunedaq.timinglibs.timinghardwaremanagerpdiinfo.Info\" WITH KEY=\"partition_id\" WHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Message Reporting",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT severity,time,application_name,message,issue_name,host_name\nFROM public.\"ErrorReports\"\nWHERE partition='${partition}' AND time >= ${__from} AND time <= ${__to}\nORDER BY -time\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Generic Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timestamp",
   "type": "timeseries",
   "description": "Displays timestamp data.\n\nThe left axis indicates the current timestamp value in seconds from the UNIX epoch. The actual timestamp value is 62,500,000 times this number.\n\nThe right axis indicates the average change between two successive timestamps over one minute. This should be 62,500,000 from the 62.5MHz frequency.",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Timestamp ([[tag_partition_id]])",
     "groupBy": [
      { "params": [ "partition_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.timing.timingfirmwareinfo.MasterMonitorData",
     "query": "SELECT \"timestamp\" / 62500000 AS \"Timestamp\" FROM \"dunedaq.timing.timingfirmwareinfo.MasterMonitorData\" WHERE (\"partition_id\" =~ /^$partition$/) AND $timeFilter GROUP BY \"partition_id\"",
     "select": [
      [
       { "params": [ "timestamp" ], "type": "field" },
       { "params": [ "/ 62500000" ], "type": "math" },
       { "params": [ "Timestamp" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=~", "value": "/^$partition$/" }
     ]
    },
    {
     "alias": "Δ timestamp ([[tag_partition_id]])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "partition_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.timing.timingfirmwareinfo.MasterMonitorData",
     "query": "SELECT derivative(mean(\"timestamp\"), 1s) AS \"Timestamp change\" FROM \"dunedaq.timing.timingfirmwareinfo.MasterMonitorData\" WHERE (\"partition_id\" =~ /^$partition$/) AND time >= now() - 3h - 1m and time <= now() GROUP BY time(1m), \"partition_id\"",
     "select": [
      [
       { "params": [ "timestamp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Timestamp change" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Master information",
   "type": "state-timeline",
   "description": "Displays the status of the MMCM and PLL over time.\n\nNote the PLL is expected to be \"Bad\" unless an upstream device is connected.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData",
     "query": "SELECT min(\"mmcm_ok\") AS \"MMCM OK\", min(\"pll_ok\") AS \"PLL Locked\" FROM \"dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData\" WHERE (\"partition_id\" =~ /^$partition$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mmcm_ok" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "MMCM OK" ], "type": "alias" }
      ],
      [
       { "params": [ "pll_ok" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "PLL Locked" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "PLL faults",
   "type": "stat",
   "description": "Displays the \"pll_sticky\" flag: This goes low if the device has a PLL (Phase-Locked Loop) fault, and remains low until the next reset.\n\nCurrently expected to always be low, since this flag will be set as low after the reset before the PLL becomes ready.",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData",
     "query": "SELECT \"pll_sticky\" FROM \"dunedaq.timing.timinghardwareinfo.TimingTLUMonitorData\",\"dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData\",\"dunedaq.timing.timinghardwareinfo.TimingFIBMonitorData\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter",
     "select": [
      [
       { "params": [ "pll_sticky" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MMCM faults",
   "type": "stat",
   "description": "Displays the \"mmcm_sticky\" flag. This flag will go low if a fault is detected in the MMCM (Mixed-Mode Clock Manager), and remain low until the device is reset.\n\nCurrently expected to always be low, since this flag will be set as low after the reset before the MMCM becomes ready.",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData",
     "query": "SELECT \"mmcm_sticky\" FROM \"dunedaq.timing.timinghardwareinfo.TimingTLUMonitorData\",\"dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData\",\"dunedaq.timing.timinghardwareinfo.TimingMIBMonitorData\",\"dunedaq.timing.timinghardwareinfo.TimingFIBMonitorData\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter",
     "select": [
      [
       { "params": [ "pll_sticky" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timing Master Controller command counts",
   "type": "bargauge",
   "description": "Counts of commands in the TMC.\n - Reset commands: Number of requests sent to reset the master.\n - Status commands: Number of requests sent to get the status of the master.\n - Timestamp set commands: Number of requests sent to set the timestamp in the master device.\n - Delay set commands: Number of requests sent to set the delay of a connected endpoint device.\n - Generic commands: Number of commands requests (i.e. echo).",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.timingmastercontrollerinfo.Info",
     "select": [
      [
       { "params": [ "sent_master_io_reset_cmds" ], "type": "field" },
       { "params": [ "Reset requests" ], "type": "alias" }
      ],
      [
       { "params": [ "sent_master_print_status_cmds" ], "type": "field" },
       { "params": [ "Status requests" ], "type": "alias" }
      ],
      [
       { "params": [ "sent_master_set_timestamp_cmds" ], "type": "field" },
       { "params": [ "Timestamp set requests" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sent_master_set_endpoint_delay_cmds"
        ],
        "type": "field"
       },
       { "params": [ "Delay set requests" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sent_master_send_fl_command_cmds"
        ],
        "type": "field"
       },
       { "params": [ "Command requests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Timing Hardware Interface command counts",
   "type": "bargauge",
   "description": "Counts of commands in the THI.\n - Received commands: Number of command requests received by the THI.\n - Accepted commands: Number of commands received by THI which are recognised.\n - Rejected commands: Number of commands received by THI which are not recognised.\n - Failed commands: Number of commands accepted by THI which fail in execution.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.timinghardwaremanagerpdiinfo.Info",
     "select": [
      [
       { "params": [ "received_hw_commands_counter" ], "type": "field" },
       { "params": [ "Recieved commands" ], "type": "alias" }
      ],
      [
       { "params": [ "accepted_hw_commands_counter" ], "type": "field" },
       { "params": [ "Accepted commands" ], "type": "alias" }
      ],
      [
       { "params": [ "rejected_hw_commands_counter" ], "type": "field" },
       { "params": [ "Rejected commands" ], "type": "alias" }
      ],
      [
       { "params": [ "failed_hw_commands_counter" ], "type": "field" },
       { "params": [ "Failed commands" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Expert Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PC059 Active mux",
     "type": "stat",
     "description": "Only active is the master is a pc059 board.\n\nIndicates which mux (0-7) is selected.",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData",
       "query": "SELECT \"sfp_flt\" FROM \"dunedaq.timing.timinghardwareinfo.TimingTLUMonitorData\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "active_sfp_mux" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "partition_id", "operator": "=~", "value": "/^$partition$/" }
       ]
      }
     ]
    },
    {
     "title": "PC059 data",
     "type": "state-timeline",
     "description": "Only active if the master is a pc059 board.\n\nIndicates the SFP statuses of the upstream and downstream SFPs.\n\nNote LOS (Loss Of Signal) is expected to be \"Bad\" if no SFP is connected.",
     "gridPos": { "h": 12, "w": 21, "x": 3, "y": 32 },
     "targets": [
      {
       "measurement": "dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData",
       "query": "SELECT\n  min(\"usfp_los\") AS \"Upstream SFP LOS\",\n  min(\"usfp_flt\") AS \"Upstream SFP fault\",\n  (min(\"sfp_los\")&1) AS \"SFP 0 LOS\",\n  (min(\"sfp_los\")&2)/2 AS \"SFP 1 LOS\",\n  (min(\"sfp_los\")&4)/4 AS \"SFP 2 LOS\",\n  (min(\"sfp_los\")&8)/8 AS \"SFP 3 LOS\",\n  (min(\"sfp_los\")&16)/16 AS \"SFP 4 LOS\",\n  (min(\"sfp_los\")&32)/32 AS \"SFP 5 LOS\",\n  (min(\"sfp_los\")&64)/64 AS \"SFP 6 LOS\",\n  (min(\"sfp_los\")&128)/128 AS \"SFP 7 LOS\"\nFROM \"dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "usfp_los" ], "type": "field" },
         { "params": [ "Upstream SFP LOS" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "TLU data",
     "type": "state-timeline",
     "description": "Only active is the master is a TLU.\n\nIndicates the status of the SFP of a TLU device.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "measurement": "dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData",
       "query": "SELECT min(\"sfp_flt\") AS \"SFP Fault\" FROM \"dunedaq.timing.timinghardwareinfo.TimingTLUMonitorData\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "sfp_los" ], "type": "field" },
         { "params": [ "alias" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "MIB data",
     "type": "state-timeline",
     "description": "Only active if the master is a MIB.\n\nIndicates the statuses of the SFPs on the MIB.\n\nNote LOS (Loss Of Signal) is expected to be \"Bad\" if there is not SFP attached.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "measurement": "dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData",
       "query": "SELECT\n  (min(\"sfp_0_flt\") ^ true) AS \"SFP 0 Fault\",\n  (min(\"sfp_0_los\") ^ true) AS \"SFP 0 LOS\",\n  (min(\"sfp_1_flt\") ^ true) AS \"SFP 1 Fault\",\n  (min(\"sfp_1_los\") ^ true) AS \"SFP 1 LOS\",\n  (min(\"sfp_2_flt\") ^ true) AS \"SFP 2 Fault\",\n  (min(\"sfp_2_los\") ^ true) AS \"SFP 2 LOS\"\nFROM \"dunedaq.timing.timinghardwareinfo.TimingPC059MonitorData\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "sfp_los" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}