{
 "title": "Trigger Flow",
 "tags": [
  "v5.5.0",
  "Subsystem"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT \"session\" FROM (SELECT \"state\",\"session\" FROM \"dunedaq.appfwk.opmon.AppInfo\" WHERE $timeFilter)"
   },
   {
    "name": "tp_handler",
    "label": "TP Handlers",
    "query": "SELECT \"element\" FROM (SELECT \"tp_received_count\", \"element\" FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter)"
   },
   {
    "name": "ta_handler",
    "label": "TA Handlers",
    "query": "SELECT \"element\" FROM (SELECT \"ta_received_count\", \"element\" FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter)"
   },
   {
    "name": "tc_handler",
    "label": "TA Handlers",
    "query": "SELECT \"element\" FROM (SELECT \"tc_received_count\", \"element\" FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter)"
   },
   {
    "name": "element",
    "label": "Trigger elements",
    "query": "SELECT \"element\" FROM (SELECT \"rate_payloads_consumed\", \"element\" FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND \"subelement\" =~ /T[^P]Processor/ AND $timeFilter)"
   },
   {
    "name": "type",
    "label": "Trigger Type",
    "query": "SELECT type FROM (SELECT received, type FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE session='${session}' AND $timeFilter)"
   },
   {
    "name": "MLT",
    "label": "MLT module name",
    "query": "SELECT last(element) FROM (SELECT \"td_total_count\", \"element\"FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter )"
   },
   {
    "name": "RandomTCM",
    "label": "Random TC Maker name",
    "query": "SELECT last(element) FROM (SELECT \"tc_sent_count\", \"element\" FROM \"dunedaq.trigger.opmon.RandomTCMakerInfo\" WHERE \"session\" = '${session}' AND $timeFilter )"
   },
   {
    "name": "HSI",
    "label": "HSI name",
    "query": "SELECT last(element) FROM (SELECT \"received_events_count\", \"element\" FROM \"dunedaq.trigger.opmon.HSISourceModelInfo\" WHERE \"session\" = '${session}' AND $timeFilter )"
   }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$session",
     "query": "SELECT \"run_number\" FROM \"dunedaq.drunc.opmon.RunInfo\" WHERE \"session\"='${session}' AND $timeFilter AND run_number>0"
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Module Level Trigger",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TD Total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_total_count\"), 1s) FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD Message received",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_msg_received_count\"), 1s) FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "tc_received_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD Sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)  ",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD Inhibited",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_inhibited_count\"), 1s) FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)   ",
     "select": [
      [
       { "params": [ "td_inhibited_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD Paused",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_paused_count\"), 1s) FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)   ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"td_queue_timeout_expired_err_count\"), 1s) FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)   ",
     "select": [
      [
       {
        "params": [
         "td_queue_timeout_expired_err_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "TC Processor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TC received",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_received_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC ignored",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_ignored_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD created",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_created_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "tc_received_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD dropped",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_dropped_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD failed bitword",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_failed_bitword_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD cleared",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_cleared_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "TC Processor per TC count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TD created ",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_created_tc_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_sent_tc_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "tc_received_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD dropped",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_dropped_tc_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD failed bitword",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_failed_bitword_tc_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TD cleared",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tds_cleared_tc_count\"), 1s) FROM \"dunedaq.trigger.opmon.TCProcessorInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  { "title": "Type flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "${type}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "repeat": "type",
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    { "expression": "${I}/${H}", "type": "math" },
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datafloworchestratorinfo.TriggerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"received\")),1s) FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE \"session\"::tag = '${session}' AND type=~ /k${type}/ AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id::tag", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Completed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datafloworchestratorinfo.TriggerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"completed\")),1s) FROM \"dunedaq.dfmodules.opmon.TriggerInfo\" WHERE \"session\"::tag = '${session}' AND type=~ /k${type}/ AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id::tag", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datafloworchestratorinfo.TriggerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"sent\")),1s) FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE \"session\"::tag = '${session}' AND type=~ /k${type}/ AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id::tag", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Sent failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datafloworchestratorinfo.TriggerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"failed_send\")),1s) FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE \"session\"::tag = '${session}' AND type=~ /k${type}/ AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id::tag", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Inhibited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datafloworchestratorinfo.TriggerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"inhibited\")),1s) FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE \"session\"::tag = '${session}' AND type=~ /k${type}/ AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id::tag", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Paused",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datafloworchestratorinfo.TriggerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"paused\")),1s) FROM \"dunedaq.trigger.opmon.TriggerDecisionInfo\" WHERE \"session\"::tag = '${session}' AND type=~ /k${type}/ AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id::tag", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "To Dataflow",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datafloworchestratorinfo.TriggerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"received\")),1s) FROM \"dunedaq.dfmodules.opmon.TriggerInfo\" WHERE \"session\"::tag = '${session}' AND type=~ /k${type}/ AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id::tag", "operator": "=", "value": "maroda" }
     ]
    }
   ]
  },
  { "title": "Plugins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HSI sources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Received signals",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"received_events_count\"), 1s) FROM \"dunedaq.trigger.opmon.HSISourceModelInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TCs made",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tcs_made_count\"), 1s) FROM \"dunedaq.trigger.opmon.HSISourceModelInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TCs sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tcs_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.HSISourceModelInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC dropped",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tcs_dropped_count\"), 1s) FROM \"dunedaq.trigger.opmon.HSISourceModelInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Random TC Maker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TC made",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_made_count\"), 1s) FROM \"dunedaq.trigger.opmon.RandomTCMakerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.RandomTCMakerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC failed sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_failed_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.RandomTCMakerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "TP Maker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TP read",
     "query": "SELECT non_negative_derivative(last(\"tp_made_count\"), 1s) FROM \"dunedaq.trigger.opmon.TPReplayModuleInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "TP vector made",
     "query": "SELECT non_negative_derivative(last(\"tpv_made_count\"), 1s) FROM \"dunedaq.trigger.opmon.TPReplayModuleInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "TP vector failed sent",
     "query": "SELECT non_negative_derivative(last(\"tpv_failed_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.TPReplayModuleInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Global TP Processors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TP received",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT sum(data) FROM (SELECT non_negative_derivative(last(\"tp_received_count\"), 1s) AS \"data\" FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${tp_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TA made ",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT sum(data) FROM ( SELECT non_negative_derivative(last(\"ta_made_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${tp_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TA sent ",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT sum(data) FROM ( SELECT non_negative_derivative(last(\"ta_sent_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${tp_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TA failed sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT sum(data) FROM  ( SELECT non_negative_derivative(last(\"ta_failed_sent_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${tp_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Global TA Processors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TA received",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT sum(data) FROM ( SELECT non_negative_derivative(last(\"ta_received_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${ta_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC made",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT sum(data) FROM  ( SELECT non_negative_derivative(last(\"tc_made_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${ta_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT sum(data) FROM  ( SELECT non_negative_derivative(last(\"tc_sent_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${ta_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC failed sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT sum(data) FROM ( SELECT non_negative_derivative(last(\"tc_failed_sent_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${ta_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null) ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "TP Processor for ${tp_handler}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "repeat": "tp_handler",
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TP received",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tp_received_count\"), 1s) FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${tp_handler}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TA made ",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"ta_made_count\"), 1s) FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${tp_handler}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TA sent ",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"ta_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${tp_handler}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TA failed sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"ta_failed_sent_count\"), 1s) FROM \"dunedaq.trigger.opmon.TPProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${tp_handler}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "TA Processor for ${ta_handler}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "repeat": "ta_handler",
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "TA received",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"ta_received_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${ta_handler}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC made",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_made_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${ta_handler}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_sent_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${ta_handler}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "TC failed sent",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(last(\"tc_failed_sent_count\"), 1s) AS data FROM \"dunedaq.trigger.opmon.TAProcessorInfo\" WHERE \"session\" = '${session}' AND \"element\"=~/${ta_handler}/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "MLT Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_in\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"element\"::tag = '${MLT}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_out\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"element\"::tag = '${MLT}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    },
    {
     "alias": "Difference",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_out\")-mean(\"latency_in\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"element\"::tag = '${MLT}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    }
   ]
  },
  {
   "title": "TC Processor Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_element - in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_in\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"subelement\"::tag = 'TCProcessor' AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    },
    {
     "alias": "$tag_element - out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_out\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"subelement\"::tag = 'TCProcessor' AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    },
    {
     "alias": "$tag_element - Diff",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_out\")-mean(\"latency_in\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"subelement\"::tag = 'TCProcessor' AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    }
   ]
  },
  {
   "title": "TA Processor Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_element - in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_in\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"element\"::tag =~ /${ta_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    },
    {
     "alias": "$tag_element - out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_out\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}'  AND \"element\"::tag =~ /${ta_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    }
   ]
  },
  {
   "title": "TD window boundaries vs system time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "end",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.ModuleLevelTriggerRequestLatency",
     "query": "SELECT mean(\"latency_window_end\") FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerRequestLatency\" WHERE session::tag = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_window_end" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "start",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.ModuleLevelTriggerRequestLatency",
     "query": "SELECT mean(\"latency_window_start\") FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerRequestLatency\" WHERE session::tag = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_window_end" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Difference",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.ModuleLevelTriggerRequestLatency",
     "query": "SELECT mean(\"latency_window_start\") - mean(\"latency_window_end\") FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerRequestLatency\" WHERE session::tag = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_window_end" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TC Plugin Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_element - in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_in\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"element\"::tag =~ /${HSI}/ AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    },
    {
     "alias": "$tag_element - out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_out\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"element\"::tag =~ /${HSI}/ AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    },
    {
     "alias": "$tag_element - out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_out\") FROM \"dunedaq.trigger.opmon.TriggerLatencyStandalone\" WHERE session::tag = '${session}' AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    }
   ]
  },
  {
   "title": "TP Processor Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_element - in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_in\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}' AND \"element\"::tag =~ /${tp_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    },
    {
     "alias": "$tag_element - out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.opmon.TriggerLatency",
     "query": "SELECT mean(\"latency_out\") FROM \"dunedaq.trigger.opmon.TriggerLatency\" WHERE session::tag = '${session}'  AND \"element\"::tag =~ /${tp_handler}/ AND $timeFilter GROUP BY element, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latency_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "element::tag", "operator": "=", "value": "def-mlt-conf" }
     ]
    }
   ]
  },
  { "title": "Livetime counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Livetime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Live",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT mean(\"lc_klive\") FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "Paused",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT mean(\"lc_kpaused\") FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    },
    {
     "alias": "Dead",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT mean(\"lc_kdead\") FROM \"dunedaq.trigger.opmon.ModuleLevelTriggerInfo\" WHERE \"session\" = '${session}' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "np02-coldbox" },
      { "condition": "AND", "key": "source_id", "operator": "=", "value": "np02-coldbox.trigger.mlt" }
     ]
    }
   ]
  },
  { "title": "Timestamps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Last DAQ Timestamp for TPProcessors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "repeat": "application",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT last(\"last_daq_timestamp\")/1000000000 FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND element =~/^${tp_handler}$/ AND \"last_daq_timestamp\">0 AND $timeFilter GROUP BY \"element\", time($__interval)"
    },
    {
     "alias": "Spread",
     "query": "SELECT spread(\"last_daq_timestamp\") FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND element =~/^${tp_handler}$/ AND \"last_daq_timestamp\">0 AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Last DAQ Timestamp for TAProcessors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT last(\"last_daq_timestamp\")/1000000000 FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND element =~/^${ta_handler}$/ AND \"last_daq_timestamp\">0 AND $timeFilter GROUP BY \"element\", time($__interval)"
    },
    {
     "alias": "Spread",
     "query": "SELECT spread(\"last_daq_timestamp\") FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND element =~/^${ta_handler}$/ AND \"last_daq_timestamp\">0 AND $timeFilter GROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Last DAQ Timestamp for TCProcessors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_element",
     "query": "SELECT last(\"last_daq_timestamp\")/1000000000 FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND element =~/^${tc_handler}$/ AND \"last_daq_timestamp\">0 AND $timeFilter GROUP BY \"element\", time($__interval)"
    }
   ]
  },
  { "title": "Data Handling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Processors - receiving rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT mean(\"rate_payloads_consumed\")*1000 FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\" = '${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval), \"element\"",
     "select": [
      [
       { "params": [ "rate_payloads_consumed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers - Number of elements",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 97 },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT mean(\"num_buffer_elements\") FROM \"dunedaq.datahandlinglibs.opmon.LatencyBufferInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval), \"element\" fill(null)",
     "select": [
      [
       { "params": [ "num_buffer_elements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT sum(\"data\") FROM ( SELECT mean(\"num_buffer_elements\") AS \"data\" FROM \"dunedaq.datahandlinglibs.opmon.LatencyBufferInfo\" WHERE  \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval), \"element\" fill(null) ) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "num_buffer_elements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers - Operational rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 97 },
   "targets": [
    {
     "alias": "Cleanups",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_buffer_cleanups\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_buffer_cleanups" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    },
    {
     "alias": "Insert failures",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_lb_insert_failures\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/  AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "num_payloads_overwritten" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Request answering time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Partition average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT sum(\"tot_request_response_time\")/sum(\"num_requests_handled\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND \"num_requests_handled\">0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT sum(\"tot_request_response_time\")/sum(\"num_requests_handled\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND \"num_requests_handled\">0 AND $timeFilter GROUP BY \"element\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT min(\"min_request_response_time\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND \"num_requests_handled\">0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RawDataProcessorInfo",
     "query": "SELECT max(\"max_request_response_time\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND \"num_requests_handled\">0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_tps_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Waiting requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 104 },
   "targets": [
    {
     "alias": "$tag_element",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT sum(\"num_requests_waiting\") FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval), \"element\"",
     "select": [
      [
       { "params": [ "num_requests_waiting" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 104 },
   "targets": [
    {
     "alias": "Total ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Found",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_found\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_found" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Delayed ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_delayed\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_delayed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Bad ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_bad\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_bad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Old window",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_old_window\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Timing out ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_timed_out\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Uncategorized",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_uncategorized\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_uncategorized" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  { "title": "Single elements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Buffers - Operational rates for ${element}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 112 },
   "repeat": "element",
   "targets": [
    {
     "alias": "Cleanups",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_buffer_cleanups\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_buffer_cleanups" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    },
    {
     "alias": "Insert Failures",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_lb_insert_failures\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/  AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "num_payloads_overwritten" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rates for ${element}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 112 },
   "repeat": "element",
   "targets": [
    {
     "alias": "Total ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests\")), 1s) FROM \"dunedaq.datahandlinglibs.opmon.DataHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Found",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_found\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_found" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Delayed ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_delayed\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_delayed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Bad ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_bad\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_bad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Old window",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_old_window\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Timing out ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.ReadoutInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_timed_out\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "Uncategorized",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.datahandlinglibs.readoutinfo.RequestHandlerInfo",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"num_requests_uncategorized\")), 1s)  FROM \"dunedaq.datahandlinglibs.opmon.RequestHandlerInfo\" WHERE \"session\"='${session}' AND \"element\" =~ /^${element}$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_requests_uncategorized" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  }
 ]
}