{
 "title": "Timing",
 "tags": [
  "Coldbox",
  "Global"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Fwk Current Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timing App Status History",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 6, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "SELECT \"json.appinfo.data.busy\" FROM \"timing_app\"",
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hardware Manager PDI Accepted/Rejected",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Accepted",
     "measurement": "dunedaq.timinglibs.timinghardwaremanagerpdiinfo.Info",
     "select": [
      [
       { "params": [ "accepted_hw_commands_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Rejected",
     "measurement": "dunedaq.timinglibs.timinghardwaremanagerpdiinfo.Info",
     "select": [
      [
       { "params": [ "rejected_hw_commands_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Timing App Errors", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 19, "y": 1 } },
  {
   "title": "App Fwk Busy State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "select": [
      [
       { "params": [ "busy" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Rejected",
     "measurement": "dunedaq.timinglibs.timinghardwaremanagerpdiinfo.Info",
     "select": [
      [
       { "params": [ "rejected_hw_commands_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "App Fwk Error State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hardware Manager PDI Received/Failed",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Received",
     "measurement": "dunedaq.timinglibs.timinghardwaremanagerpdiinfo.Info",
     "select": [
      [
       { "params": [ "received_hw_commands_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Failed",
     "measurement": "dunedaq.timinglibs.timinghardwaremanagerpdiinfo.Info",
     "select": [
      [
       { "params": [ "failed_hw_commands_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "Error State",
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Failed",
     "measurement": "dunedaq.timinglibs.timinghardwaremanagerpdiinfo.Info",
     "select": [
      [
       { "params": [ "failed_hw_commands_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Controller Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timing Master Controller Info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "IO reset",
       "measurement": "dunedaq.timinglibs.timingmastercontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_master_io_reset_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Print status",
       "measurement": "dunedaq.timinglibs.timingmastercontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_master_print_status_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Set timestamp",
       "measurement": "dunedaq.timinglibs.timingmastercontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_master_set_timestamp_cmds" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Timing Partition Controller Info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Configure",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_configure_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Disable",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_disable_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Disable triggers",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         {
          "params": [
           "sent_partition_disable_triggers_cmds"
          ],
          "type": "field"
         }
        ]
       ]
      },
      {
       "alias": "Enable",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_enable_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Enable triggers",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         {
          "params": [
           "sent_partition_enable_triggers_cmds"
          ],
          "type": "field"
         }
        ]
       ]
      },
      {
       "alias": "Print status",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         {
          "params": [
           "sent_partition_print_status_cmds"
          ],
          "type": "field"
         }
        ]
       ]
      },
      {
       "alias": "Start",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_start_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Stop",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_stop_cmds" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Fan Out Controller Info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "alias": "IO reset",
       "measurement": "dunedaq.timinglibs.timingfanoutcontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_io_reset_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Print status",
       "measurement": "dunedaq.timinglibs.timingfanoutcontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_print_status_cmds" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "IO Reset Counter",
       "measurement": "dunedaq.timinglibs.timingmastercontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_master_io_reset_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Print Status Counter",
       "measurement": "dunedaq.timinglibs.timingmastercontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_master_print_status_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Set Timestamp Counter",
       "measurement": "dunedaq.timinglibs.timingmastercontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_master_set_timestamp_cmds" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Configure",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_configure_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Disable",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_disable_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Disable triggers",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         {
          "params": [
           "sent_partition_disable_triggers_cmds"
          ],
          "type": "field"
         }
        ]
       ]
      },
      {
       "alias": "Enable",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_enable_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Enable triggers",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         {
          "params": [
           "sent_partition_enable_triggers_cmds"
          ],
          "type": "field"
         }
        ]
       ]
      },
      {
       "alias": "Print status",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         {
          "params": [
           "sent_partition_print_status_cmds"
          ],
          "type": "field"
         }
        ]
       ]
      },
      {
       "alias": "Start",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_start_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Stop",
       "measurement": "dunedaq.timinglibs.timingpartitioncontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_partition_stop_cmds" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "IO reset counter",
       "measurement": "dunedaq.timinglibs.timingfanoutcontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_io_reset_cmds" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Print status counter",
       "measurement": "dunedaq.timinglibs.timingfanoutcontrollerinfo.Info",
       "select": [
        [
         { "params": [ "sent_print_status_cmds" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "HSI Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HSI Average Buffer Occupancy",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Average buffer occupancy",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "average_buffer_occupancy" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HSI Events Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       {
        "params": [
         "failed_to_send_hsi_events_counter"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HSI events sent counter",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "sent_hsi_events_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "HSI events readout counter",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "readout_hsi_events_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sent Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "last_sent_timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Readout Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "last_readout_timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "alias": "Failed to send HSI event",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       {
        "params": [
         "failed_to_send_hsi_events_counter"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HSI + HSI Write to disk TEST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Counters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "Readout",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "readout_hsi_events_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Sent",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "sent_hsi_events_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Received",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "received_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Written",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "written_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Failed to Send",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       {
        "params": [
         "failed_to_send_hsi_events_counter"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Failed to Write",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "failed_to_write_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed to send",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       {
        "params": [
         "failed_to_send_hsi_events_counter"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HSI events sent counter",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "sent_hsi_events_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "HSI events readout counter",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "readout_hsi_events_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "HSI events received",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "received_counter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "HSI events written",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "written_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed to write",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Failed to write",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "failed_to_write_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sent Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "last_sent_timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Readout Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "last_readout_timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HSI Average Buffer Occupancy",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Average buffer occupancy",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       { "params": [ "average_buffer_occupancy" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "alias": "Failed to send HSI event",
     "measurement": "dunedaq.timinglibs.hsireadoutinfo.Info",
     "select": [
      [
       {
        "params": [
         "failed_to_send_hsi_events_counter"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Received Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last Received Timestamp",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "last_received_timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Written Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last Written Timestamp",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "last_written_timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "alias": "Failed to write HSI event",
     "measurement": "dunedaq.timinglibs.hsieventtofileinfo.Info",
     "select": [
      [
       { "params": [ "failed_to_write_counter" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}