{
 "title": "DAQ overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SELECT partition FROM public.\"ErrorReports\""
   },
   { "name": "df_application", "label": "DataFlow Application", "query": "dataflow" },
   { "name": "TRBInstance", "label": "TRB Instance", "query": "trb" },
   { "name": "data_writer", "label": "Data Writer Instance", "query": "datawriter" },
   { "name": "trigger_app", "label": "Trigger App", "query": "trigger" },
   { "name": "trigger_module", "label": "Trigger Module", "query": "mlt" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "query": "SELECT \"state\" FROM \"dunedaq.appfwk.appinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}' OR \"source_id\" = '${partition}_${df_application}') AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger" },
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" }
     ]
    }
   ]
  },
  {
   "title": "App Fwk Error State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.appfwk.appinfo.Info",
     "query": "SELECT \"error\" FROM \"dunedaq.appfwk.appinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}' OR \"source_id\" = '${partition}_${df_application}') AND $timeFilter",
     "select": [
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" },
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_trigger" }
     ]
    }
   ]
  },
  {
   "title": "Run time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dunedaq.rcif.runinfo.Info",
     "query": "SELECT \"runtime\" FROM \"dunedaq.rcif.runinfo.Info\" WHERE (\"source_id\" = '${partition}_${df_application}') AND $timeFilter",
     "select": [
      [
       { "params": [ "runtime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" }
     ]
    }
   ]
  },
  {
   "title": "Run number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "dunedaq.rcif.runinfo.Info",
     "query": "SELECT \"runno\" FROM \"dunedaq.rcif.runinfo.Info\" WHERE (\"source_id\" = '${partition}_${df_application}') AND $timeFilter",
     "select": [
      [
       { "params": [ "runno" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "source_id", "operator": "=", "value": "maroda_test_dataflow" }
     ]
    }
   ]
  },
  {
   "title": "Processed triggers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT \"records_received\" FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = '${partition}_${df_application}.${data_writer}') AND $timeFilter",
     "select": [
      [
       { "params": [ "records_received" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    }
   ]
  },
  { "title": "Message reporting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Message Reporting",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT time,severity,application_name,issue_name,message,host_name\nFROM public.\"ErrorReports\"\nWHERE partition='${partition}'\nORDER BY -time\n"
    }
   ]
  },
  { "title": "Operational monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Event Builder Information",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "avg ms per TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT mean(\"average_millisecond_per_trigger\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}_${df_application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "average_millisecond_per_trigger"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Trigger Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Generated triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(\"td_total_count\", 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}.${trigger_module}') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Sent triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(\"td_sent_count\", 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}.${trigger_module}') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Completed TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT non_negative_derivative(mean(\"records_received\"), 1s) FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = '${partition}_${df_application}.${data_writer}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "records_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    },
    {
     "alias": "Written TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT non_negative_derivative(mean(\"records_written\"), 1s) FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = '${partition}_${df_application}.${data_writer}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "records_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Writer Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "GiBytes " }
   ],
   "targets": [
    {
     "alias": "written GiB",
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT non_negative_derivative(distinct(\"bytes_output\"), 1s)  / 1073741824 FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = '${partition}_dataflow.${data_writer}') AND $timeFilter GROUP BY time($__interval) \nfill(null)",
     "select": [
      [
       { "params": [ "bytes_output" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "${partition}_dataflow.datawriter"
      }
     ]
    }
   ]
  },
  {
   "title": "Trigger & HSI Information",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Received triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"tc_received_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}.${trigger_module}') AND $timeFilter",
     "select": [
      [
       { "params": [ "tc_received_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Sent triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"td_sent_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}.${trigger_module}') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Inhibited triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"td_inhibited_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}.${trigger_module}') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_inhibited_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "Paused triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"td_paused_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}.${trigger_module}') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "total_triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"td_total_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_${trigger_app}.${trigger_module}') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Link Handler Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.readout.datalinkhandlerinfo.Info",
     "query": "SELECT retry_request FROM \"dunedaq.readout.datalinkhandlerinfo.Info\"",
     "select": [
      [
       { "params": [ "retry_request" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.readout.datalinkhandlerinfo.Info",
     "query": "SELECT request_window_too_old FROM \"dunedaq.readout.datalinkhandlerinfo.Info\"",
     "select": [
      [
       { "params": [ "request_window_too_old" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}