{
 "title": "General",
 "description": "General dashboard",
 "tags": [
  "MRoda",
  "General"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "partition", "label": "Partition name", "query": "gio_test,global" },
   { "name": "application", "label": "Readout Application", "query": "0,1,2,3,4,5,6,7" },
   { "name": "link", "label": "Link Handler", "query": "0,1,2,3,4,5,6,7" }
  ]
 },
 "panels": [
  {
   "title": "ERS Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time,severity,application_name,issue_name,message,host_name FROM public.\"ErrorReports\" WHERE partition=${partition}\nORDER BY -time"
    }
   ]
  },
  {
   "title": "Trigger rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Trigger rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT non_negative_derivative(distinct(\"td_sent_count\"), 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_trigger.mlt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Trigger & HSI Information",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "sent_hs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.timinglibs.fakehsieventgeneratorinfo.Info",
     "query": "SELECT sent_hsi_events_counter FROM \"dunedaq.timinglibs.fakehsieventgeneratorinfo.Info\" ",
     "select": [
      [
       { "params": [ "sent_hsi_events_counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_hsi.fhsig" }
     ]
    },
    {
     "alias": "sent_triggers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT td_sent_count FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\"",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger.mlt" }
     ]
    },
    {
     "alias": "generated_triggers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT td_total_count FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" ",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger.mlt" }
     ]
    },
    {
     "alias": "inhibited_triggers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT td_inhibited_count FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" ",
     "select": [
      [
       { "params": [ "td_inhibited_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Selected Link Handler Information",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "data requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.datalinkhandlerinfo.Info",
     "query": "SELECT mean(\"requests\") FROM \"dunedaq.readout.datalinkhandlerinfo.Info\" WHERE (\"source_id\" = '${partition}_ruemu${application}.datahandler_${link}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    },
    {
     "alias": "satisfied requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.readout.datalinkhandlerinfo.Info",
     "query": "SELECT mean(\"found_requested\") FROM \"dunedaq.readout.datalinkhandlerinfo.Info\" WHERE (\"source_id\" = '${partition}_ruemu${application}.datahandler_${link}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "found_requested" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_ruemu0.datahandler_0"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Builder Information",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "avg ms per TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "select": [
      [
       {
        "params": [
         "average_millisecond_per_trigger"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Data Writer Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "GiB/s" }
   ],
   "targets": [
    {
     "alias": "Written on disc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT non_negative_derivative(distinct(\"bytes_output\"), 1s)  / 1073741824 FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = 'maroda_test_dataflow.datawriter') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_output" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Writer Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Trigger records written" }
   ],
   "targets": [
    {
     "alias": "Received TRs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT records_received FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = 'gio_test_dataflow.datawriter')",
     "select": [
      [
       { "params": [ "records_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    },
    {
     "alias": "Written TRs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT records_written FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = 'gio_test_dataflow.datawriter')",
     "select": [
      [
       { "params": [ "records_written" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.datawriter"
      }
     ]
    },
    {
     "alias": "Generated TR from TRB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  }
 ]
}